// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: laneway/v1/controller.proto

package lanewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollmentClass int32

const (
	EnrollmentClass_ENROLLMENT_CLASS_UNSPECIFIED     EnrollmentClass = 0
	EnrollmentClass_ENROLLMENT_CLASS_DURABLE_NODE    EnrollmentClass = 1
	EnrollmentClass_ENROLLMENT_CLASS_EPHEMERAL_USER  EnrollmentClass = 2
	EnrollmentClass_ENROLLMENT_CLASS_REMEMBERED_USER EnrollmentClass = 3
)

// Enum value maps for EnrollmentClass.
var (
	EnrollmentClass_name = map[int32]string{
		0: "ENROLLMENT_CLASS_UNSPECIFIED",
		1: "ENROLLMENT_CLASS_DURABLE_NODE",
		2: "ENROLLMENT_CLASS_EPHEMERAL_USER",
		3: "ENROLLMENT_CLASS_REMEMBERED_USER",
	}
	EnrollmentClass_value = map[string]int32{
		"ENROLLMENT_CLASS_UNSPECIFIED":     0,
		"ENROLLMENT_CLASS_DURABLE_NODE":    1,
		"ENROLLMENT_CLASS_EPHEMERAL_USER":  2,
		"ENROLLMENT_CLASS_REMEMBERED_USER": 3,
	}
)

func (x EnrollmentClass) Enum() *EnrollmentClass {
	p := new(EnrollmentClass)
	*p = x
	return p
}

func (x EnrollmentClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollmentClass) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_controller_proto_enumTypes[0].Descriptor()
}

func (EnrollmentClass) Type() protoreflect.EnumType {
	return &file_laneway_v1_controller_proto_enumTypes[0]
}

func (x EnrollmentClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollmentClass.Descriptor instead.
func (EnrollmentClass) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{0}
}

type EnrollmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	// DER PKCS#10 CSR. The private key is never transmitted.
	Pkcs10CsrDer  []byte `protobuf:"bytes,2,opt,name=pkcs10_csr_der,json=pkcs10CsrDer,proto3" json:"pkcs10_csr_der,omitempty"`
	RequestedName string `protobuf:"bytes,3,opt,name=requested_name,json=requestedName,proto3" json:"requested_name,omitempty"`
	// The NetworkID authenticated through public bootstrap metadata. The
	// controller compares it with the token's immutable network before token
	// consumption, preventing cross-network code confusion.
	ExpectedNetworkId []byte `protobuf:"bytes,4,opt,name=expected_network_id,json=expectedNetworkId,proto3" json:"expected_network_id,omitempty"`
	// Optional client-side class expectation authenticated by the bootstrap
	// flow. A mismatch is rejected before the single-use token is consumed.
	ExpectedEnrollmentClass EnrollmentClass `protobuf:"varint,5,opt,name=expected_enrollment_class,json=expectedEnrollmentClass,proto3,enum=laneway.v1.EnrollmentClass" json:"expected_enrollment_class,omitempty"`
	// Raw 32-byte X25519 public key generated locally for the WireGuard
	// dataplane. The corresponding private key never leaves the client.
	WireguardPublicKey []byte `protobuf:"bytes,6,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_laneway_v1_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollmentRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollmentRequest) GetPkcs10CsrDer() []byte {
	if x != nil {
		return x.Pkcs10CsrDer
	}
	return nil
}

func (x *EnrollmentRequest) GetRequestedName() string {
	if x != nil {
		return x.RequestedName
	}
	return ""
}

func (x *EnrollmentRequest) GetExpectedNetworkId() []byte {
	if x != nil {
		return x.ExpectedNetworkId
	}
	return nil
}

func (x *EnrollmentRequest) GetExpectedEnrollmentClass() EnrollmentClass {
	if x != nil {
		return x.ExpectedEnrollmentClass
	}
	return EnrollmentClass_ENROLLMENT_CLASS_UNSPECIFIED
}

func (x *EnrollmentRequest) GetWireguardPublicKey() []byte {
	if x != nil {
		return x.WireguardPublicKey
	}
	return nil
}

type CertificateChain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DER leaf first, followed by intermediates. The trust anchor is distributed
	// out of band and should not normally be included.
	CertificatesDer     [][]byte `protobuf:"bytes,1,rep,name=certificates_der,json=certificatesDer,proto3" json:"certificates_der,omitempty"`
	NotAfterUnixSeconds uint64   `protobuf:"varint,2,opt,name=not_after_unix_seconds,json=notAfterUnixSeconds,proto3" json:"not_after_unix_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CertificateChain) Reset() {
	*x = CertificateChain{}
	mi := &file_laneway_v1_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateChain) ProtoMessage() {}

func (x *CertificateChain) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateChain.ProtoReflect.Descriptor instead.
func (*CertificateChain) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateChain) GetCertificatesDer() [][]byte {
	if x != nil {
		return x.CertificatesDer
	}
	return nil
}

func (x *CertificateChain) GetNotAfterUnixSeconds() uint64 {
	if x != nil {
		return x.NotAfterUnixSeconds
	}
	return 0
}

type EnrollmentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NetworkId        []byte                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId           []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CertificateChain *CertificateChain      `protobuf:"bytes,3,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	// Controller-assigned canonical overlay addresses for initial lane0 setup.
	OverlayAddresses [][]byte        `protobuf:"bytes,4,rep,name=overlay_addresses,json=overlayAddresses,proto3" json:"overlay_addresses,omitempty"`
	EnrollmentClass  EnrollmentClass `protobuf:"varint,5,opt,name=enrollment_class,json=enrollmentClass,proto3,enum=laneway.v1.EnrollmentClass" json:"enrollment_class,omitempty"`
	// Nonzero only for a fully ephemeral identity. Authentication and every
	// authorization derived from it fail closed at this UTC deadline.
	LeaseExpiresAtUnixSeconds uint64 `protobuf:"varint,6,opt,name=lease_expires_at_unix_seconds,json=leaseExpiresAtUnixSeconds,proto3" json:"lease_expires_at_unix_seconds,omitempty"`
	// The controller-authoritative key bound to network_id and node_id. Clients
	// must compare this with the locally generated public key before use.
	WireguardPublicKey []byte `protobuf:"bytes,7,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_laneway_v1_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollmentResponse) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *EnrollmentResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *EnrollmentResponse) GetCertificateChain() *CertificateChain {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

func (x *EnrollmentResponse) GetOverlayAddresses() [][]byte {
	if x != nil {
		return x.OverlayAddresses
	}
	return nil
}

func (x *EnrollmentResponse) GetEnrollmentClass() EnrollmentClass {
	if x != nil {
		return x.EnrollmentClass
	}
	return EnrollmentClass_ENROLLMENT_CLASS_UNSPECIFIED
}

func (x *EnrollmentResponse) GetLeaseExpiresAtUnixSeconds() uint64 {
	if x != nil {
		return x.LeaseExpiresAtUnixSeconds
	}
	return 0
}

func (x *EnrollmentResponse) GetWireguardPublicKey() []byte {
	if x != nil {
		return x.WireguardPublicKey
	}
	return nil
}

type RenewalRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Pkcs10CsrDer []byte                 `protobuf:"bytes,1,opt,name=pkcs10_csr_der,json=pkcs10CsrDer,proto3" json:"pkcs10_csr_der,omitempty"`
	// The current or replacement locally generated WireGuard public key. A key
	// change is committed atomically with the replacement certificate.
	WireguardPublicKey []byte `protobuf:"bytes,2,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RenewalRequest) Reset() {
	*x = RenewalRequest{}
	mi := &file_laneway_v1_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewalRequest) ProtoMessage() {}

func (x *RenewalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewalRequest.ProtoReflect.Descriptor instead.
func (*RenewalRequest) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{3}
}

func (x *RenewalRequest) GetPkcs10CsrDer() []byte {
	if x != nil {
		return x.Pkcs10CsrDer
	}
	return nil
}

func (x *RenewalRequest) GetWireguardPublicKey() []byte {
	if x != nil {
		return x.WireguardPublicKey
	}
	return nil
}

type RenewalResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CertificateChain   *CertificateChain      `protobuf:"bytes,1,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	WireguardPublicKey []byte                 `protobuf:"bytes,2,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RenewalResponse) Reset() {
	*x = RenewalResponse{}
	mi := &file_laneway_v1_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewalResponse) ProtoMessage() {}

func (x *RenewalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewalResponse.ProtoReflect.Descriptor instead.
func (*RenewalResponse) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{4}
}

func (x *RenewalResponse) GetCertificateChain() *CertificateChain {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

func (x *RenewalResponse) GetWireguardPublicKey() []byte {
	if x != nil {
		return x.WireguardPublicKey
	}
	return nil
}

type NodeConfiguration struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConfigurationEpoch  uint64                 `protobuf:"varint,1,opt,name=configuration_epoch,json=configurationEpoch,proto3" json:"configuration_epoch,omitempty"`
	OverlayAddresses    [][]byte               `protobuf:"bytes,2,rep,name=overlay_addresses,json=overlayAddresses,proto3" json:"overlay_addresses,omitempty"`
	Routes              *RouteSnapshot         `protobuf:"bytes,3,opt,name=routes,proto3" json:"routes,omitempty"`
	Policy              *PolicySnapshot        `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	EnabledCapabilities uint64                 `protobuf:"varint,5,opt,name=enabled_capabilities,json=enabledCapabilities,proto3" json:"enabled_capabilities,omitempty"`
	// Authorization is fail-closed after this UTC Unix-second deadline unless
	// the controller renews it, including through a not-modified response.
	ValidUntilUnixSeconds uint64 `protobuf:"varint,6,opt,name=valid_until_unix_seconds,json=validUntilUnixSeconds,proto3" json:"valid_until_unix_seconds,omitempty"`
	// Canonical unsigned big-endian serials of currently valid revoked
	// certificates in this network.
	RevokedCertificateSerials [][]byte `protobuf:"bytes,7,rep,name=revoked_certificate_serials,json=revokedCertificateSerials,proto3" json:"revoked_certificate_serials,omitempty"`
	// Authenticated node identities with human-readable controller names. Names
	// are selectors for operator UX only; dataplane authorization remains bound
	// to the certificate-carried node_id.
	Peers []*NodePeer `protobuf:"bytes,8,rep,name=peers,proto3" json:"peers,omitempty"`
	// Enabled relay services discovered from the authoritative controller.
	Relays []*RelayEndpoint `protobuf:"bytes,9,rep,name=relays,proto3" json:"relays,omitempty"`
	// Controller policy for the authenticated, relay-assisted candidate
	// exchange. Ephemeral endpoint candidates themselves remain on the relay
	// control channel so they are never persisted by the controller.
	CandidateExchange *CandidateExchangePolicy `protobuf:"bytes,10,opt,name=candidate_exchange,json=candidateExchange,proto3" json:"candidate_exchange,omitempty"`
	// Explicitly authorized exit gateways derived from approved exit routes.
	ExitPolicy *ExitNodePolicy `protobuf:"bytes,11,opt,name=exit_policy,json=exitPolicy,proto3" json:"exit_policy,omitempty"`
	// Health of the certificate used to authenticate this request.
	CertificateHealth                 *CertificateHealth `protobuf:"bytes,12,opt,name=certificate_health,json=certificateHealth,proto3" json:"certificate_health,omitempty"`
	EnrollmentClass                   EnrollmentClass    `protobuf:"varint,13,opt,name=enrollment_class,json=enrollmentClass,proto3,enum=laneway.v1.EnrollmentClass" json:"enrollment_class,omitempty"`
	IdentityLeaseExpiresAtUnixSeconds uint64             `protobuf:"varint,14,opt,name=identity_lease_expires_at_unix_seconds,json=identityLeaseExpiresAtUnixSeconds,proto3" json:"identity_lease_expires_at_unix_seconds,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *NodeConfiguration) Reset() {
	*x = NodeConfiguration{}
	mi := &file_laneway_v1_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfiguration) ProtoMessage() {}

func (x *NodeConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfiguration.ProtoReflect.Descriptor instead.
func (*NodeConfiguration) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{5}
}

func (x *NodeConfiguration) GetConfigurationEpoch() uint64 {
	if x != nil {
		return x.ConfigurationEpoch
	}
	return 0
}

func (x *NodeConfiguration) GetOverlayAddresses() [][]byte {
	if x != nil {
		return x.OverlayAddresses
	}
	return nil
}

func (x *NodeConfiguration) GetRoutes() *RouteSnapshot {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NodeConfiguration) GetPolicy() *PolicySnapshot {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *NodeConfiguration) GetEnabledCapabilities() uint64 {
	if x != nil {
		return x.EnabledCapabilities
	}
	return 0
}

func (x *NodeConfiguration) GetValidUntilUnixSeconds() uint64 {
	if x != nil {
		return x.ValidUntilUnixSeconds
	}
	return 0
}

func (x *NodeConfiguration) GetRevokedCertificateSerials() [][]byte {
	if x != nil {
		return x.RevokedCertificateSerials
	}
	return nil
}

func (x *NodeConfiguration) GetPeers() []*NodePeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NodeConfiguration) GetRelays() []*RelayEndpoint {
	if x != nil {
		return x.Relays
	}
	return nil
}

func (x *NodeConfiguration) GetCandidateExchange() *CandidateExchangePolicy {
	if x != nil {
		return x.CandidateExchange
	}
	return nil
}

func (x *NodeConfiguration) GetExitPolicy() *ExitNodePolicy {
	if x != nil {
		return x.ExitPolicy
	}
	return nil
}

func (x *NodeConfiguration) GetCertificateHealth() *CertificateHealth {
	if x != nil {
		return x.CertificateHealth
	}
	return nil
}

func (x *NodeConfiguration) GetEnrollmentClass() EnrollmentClass {
	if x != nil {
		return x.EnrollmentClass
	}
	return EnrollmentClass_ENROLLMENT_CLASS_UNSPECIFIED
}

func (x *NodeConfiguration) GetIdentityLeaseExpiresAtUnixSeconds() uint64 {
	if x != nil {
		return x.IdentityLeaseExpiresAtUnixSeconds
	}
	return 0
}

type NodePeer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OverlayAddresses [][]byte               `protobuf:"bytes,3,rep,name=overlay_addresses,json=overlayAddresses,proto3" json:"overlay_addresses,omitempty"`
	// Controller-authenticated WireGuard key for this exact NetworkID/NodeID.
	WireguardPublicKey []byte `protobuf:"bytes,4,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodePeer) Reset() {
	*x = NodePeer{}
	mi := &file_laneway_v1_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePeer) ProtoMessage() {}

func (x *NodePeer) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePeer.ProtoReflect.Descriptor instead.
func (*NodePeer) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{6}
}

func (x *NodePeer) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *NodePeer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodePeer) GetOverlayAddresses() [][]byte {
	if x != nil {
		return x.OverlayAddresses
	}
	return nil
}

func (x *NodePeer) GetWireguardPublicKey() []byte {
	if x != nil {
		return x.WireguardPublicKey
	}
	return nil
}

type RelayEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     []byte                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEndpoint) Reset() {
	*x = RelayEndpoint{}
	mi := &file_laneway_v1_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEndpoint) ProtoMessage() {}

func (x *RelayEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEndpoint.ProtoReflect.Descriptor instead.
func (*RelayEndpoint) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{7}
}

func (x *RelayEndpoint) GetServiceId() []byte {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *RelayEndpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RelayEndpoint) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type CandidateExchangePolicy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxCandidates       uint32                 `protobuf:"varint,2,opt,name=max_candidates,json=maxCandidates,proto3" json:"max_candidates,omitempty"`
	CandidateTtlSeconds uint32                 `protobuf:"varint,3,opt,name=candidate_ttl_seconds,json=candidateTtlSeconds,proto3" json:"candidate_ttl_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CandidateExchangePolicy) Reset() {
	*x = CandidateExchangePolicy{}
	mi := &file_laneway_v1_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateExchangePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateExchangePolicy) ProtoMessage() {}

func (x *CandidateExchangePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateExchangePolicy.ProtoReflect.Descriptor instead.
func (*CandidateExchangePolicy) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{8}
}

func (x *CandidateExchangePolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CandidateExchangePolicy) GetMaxCandidates() uint32 {
	if x != nil {
		return x.MaxCandidates
	}
	return 0
}

func (x *CandidateExchangePolicy) GetCandidateTtlSeconds() uint32 {
	if x != nil {
		return x.CandidateTtlSeconds
	}
	return 0
}

type ExitNodePolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthorizedNodeIds [][]byte               `protobuf:"bytes,1,rep,name=authorized_node_ids,json=authorizedNodeIds,proto3" json:"authorized_node_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExitNodePolicy) Reset() {
	*x = ExitNodePolicy{}
	mi := &file_laneway_v1_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitNodePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitNodePolicy) ProtoMessage() {}

func (x *ExitNodePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitNodePolicy.ProtoReflect.Descriptor instead.
func (*ExitNodePolicy) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{9}
}

func (x *ExitNodePolicy) GetAuthorizedNodeIds() [][]byte {
	if x != nil {
		return x.AuthorizedNodeIds
	}
	return nil
}

type CertificateHealth struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PresentedSerial       []byte                 `protobuf:"bytes,1,opt,name=presented_serial,json=presentedSerial,proto3" json:"presented_serial,omitempty"`
	NotAfterUnixSeconds   uint64                 `protobuf:"varint,2,opt,name=not_after_unix_seconds,json=notAfterUnixSeconds,proto3" json:"not_after_unix_seconds,omitempty"`
	RenewAfterUnixSeconds uint64                 `protobuf:"varint,3,opt,name=renew_after_unix_seconds,json=renewAfterUnixSeconds,proto3" json:"renew_after_unix_seconds,omitempty"`
	Revoked               bool                   `protobuf:"varint,4,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CertificateHealth) Reset() {
	*x = CertificateHealth{}
	mi := &file_laneway_v1_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateHealth) ProtoMessage() {}

func (x *CertificateHealth) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateHealth.ProtoReflect.Descriptor instead.
func (*CertificateHealth) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{10}
}

func (x *CertificateHealth) GetPresentedSerial() []byte {
	if x != nil {
		return x.PresentedSerial
	}
	return nil
}

func (x *CertificateHealth) GetNotAfterUnixSeconds() uint64 {
	if x != nil {
		return x.NotAfterUnixSeconds
	}
	return 0
}

func (x *CertificateHealth) GetRenewAfterUnixSeconds() uint64 {
	if x != nil {
		return x.RenewAfterUnixSeconds
	}
	return 0
}

func (x *CertificateHealth) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type ConfigurationRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	KnownConfigurationEpoch uint64                 `protobuf:"varint,1,opt,name=known_configuration_epoch,json=knownConfigurationEpoch,proto3" json:"known_configuration_epoch,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConfigurationRequest) Reset() {
	*x = ConfigurationRequest{}
	mi := &file_laneway_v1_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationRequest) ProtoMessage() {}

func (x *ConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigurationRequest) GetKnownConfigurationEpoch() uint64 {
	if x != nil {
		return x.KnownConfigurationEpoch
	}
	return 0
}

type RelayConfigurationRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	KnownConfigurationEpoch uint64                 `protobuf:"varint,1,opt,name=known_configuration_epoch,json=knownConfigurationEpoch,proto3" json:"known_configuration_epoch,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RelayConfigurationRequest) Reset() {
	*x = RelayConfigurationRequest{}
	mi := &file_laneway_v1_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayConfigurationRequest) ProtoMessage() {}

func (x *RelayConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayConfigurationRequest.ProtoReflect.Descriptor instead.
func (*RelayConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{12}
}

func (x *RelayConfigurationRequest) GetKnownConfigurationEpoch() uint64 {
	if x != nil {
		return x.KnownConfigurationEpoch
	}
	return 0
}

type RelayPeerAuthorization struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OverlayAddresses   [][]byte               `protobuf:"bytes,2,rep,name=overlay_addresses,json=overlayAddresses,proto3" json:"overlay_addresses,omitempty"`
	AuthorizedPrefixes []*IpPrefix            `protobuf:"bytes,3,rep,name=authorized_prefixes,json=authorizedPrefixes,proto3" json:"authorized_prefixes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayPeerAuthorization) Reset() {
	*x = RelayPeerAuthorization{}
	mi := &file_laneway_v1_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayPeerAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayPeerAuthorization) ProtoMessage() {}

func (x *RelayPeerAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayPeerAuthorization.ProtoReflect.Descriptor instead.
func (*RelayPeerAuthorization) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{13}
}

func (x *RelayPeerAuthorization) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *RelayPeerAuthorization) GetOverlayAddresses() [][]byte {
	if x != nil {
		return x.OverlayAddresses
	}
	return nil
}

func (x *RelayPeerAuthorization) GetAuthorizedPrefixes() []*IpPrefix {
	if x != nil {
		return x.AuthorizedPrefixes
	}
	return nil
}

type RelayConfiguration struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	NetworkId                 []byte                    `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ConfigurationEpoch        uint64                    `protobuf:"varint,2,opt,name=configuration_epoch,json=configurationEpoch,proto3" json:"configuration_epoch,omitempty"`
	Peers                     []*RelayPeerAuthorization `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	Policy                    *PolicySnapshot           `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	ValidUntilUnixSeconds     uint64                    `protobuf:"varint,5,opt,name=valid_until_unix_seconds,json=validUntilUnixSeconds,proto3" json:"valid_until_unix_seconds,omitempty"`
	RevokedCertificateSerials [][]byte                  `protobuf:"bytes,6,rep,name=revoked_certificate_serials,json=revokedCertificateSerials,proto3" json:"revoked_certificate_serials,omitempty"`
	CertificateHealth         *CertificateHealth        `protobuf:"bytes,7,opt,name=certificate_health,json=certificateHealth,proto3" json:"certificate_health,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RelayConfiguration) Reset() {
	*x = RelayConfiguration{}
	mi := &file_laneway_v1_controller_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayConfiguration) ProtoMessage() {}

func (x *RelayConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayConfiguration.ProtoReflect.Descriptor instead.
func (*RelayConfiguration) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{14}
}

func (x *RelayConfiguration) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *RelayConfiguration) GetConfigurationEpoch() uint64 {
	if x != nil {
		return x.ConfigurationEpoch
	}
	return 0
}

func (x *RelayConfiguration) GetPeers() []*RelayPeerAuthorization {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RelayConfiguration) GetPolicy() *PolicySnapshot {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *RelayConfiguration) GetValidUntilUnixSeconds() uint64 {
	if x != nil {
		return x.ValidUntilUnixSeconds
	}
	return 0
}

func (x *RelayConfiguration) GetRevokedCertificateSerials() [][]byte {
	if x != nil {
		return x.RevokedCertificateSerials
	}
	return nil
}

func (x *RelayConfiguration) GetCertificateHealth() *CertificateHealth {
	if x != nil {
		return x.CertificateHealth
	}
	return nil
}

// A successful conditional request whose immutable configuration epoch did
// not change. The fresh deadline extends the fail-closed snapshot lease.
type ConfigurationLease struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConfigurationEpoch    uint64                 `protobuf:"varint,1,opt,name=configuration_epoch,json=configurationEpoch,proto3" json:"configuration_epoch,omitempty"`
	ValidUntilUnixSeconds uint64                 `protobuf:"varint,2,opt,name=valid_until_unix_seconds,json=validUntilUnixSeconds,proto3" json:"valid_until_unix_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfigurationLease) Reset() {
	*x = ConfigurationLease{}
	mi := &file_laneway_v1_controller_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationLease) ProtoMessage() {}

func (x *ConfigurationLease) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationLease.ProtoReflect.Descriptor instead.
func (*ConfigurationLease) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigurationLease) GetConfigurationEpoch() uint64 {
	if x != nil {
		return x.ConfigurationEpoch
	}
	return 0
}

func (x *ConfigurationLease) GetValidUntilUnixSeconds() uint64 {
	if x != nil {
		return x.ValidUntilUnixSeconds
	}
	return 0
}

type CertificateRevocation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CertificateSerial  []byte                 `protobuf:"bytes,1,opt,name=certificate_serial,json=certificateSerial,proto3" json:"certificate_serial,omitempty"`
	NodeId             []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RevokedUnixSeconds uint64                 `protobuf:"varint,3,opt,name=revoked_unix_seconds,json=revokedUnixSeconds,proto3" json:"revoked_unix_seconds,omitempty"`
	Reason             string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CertificateRevocation) Reset() {
	*x = CertificateRevocation{}
	mi := &file_laneway_v1_controller_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRevocation) ProtoMessage() {}

func (x *CertificateRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRevocation.ProtoReflect.Descriptor instead.
func (*CertificateRevocation) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{16}
}

func (x *CertificateRevocation) GetCertificateSerial() []byte {
	if x != nil {
		return x.CertificateSerial
	}
	return nil
}

func (x *CertificateRevocation) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *CertificateRevocation) GetRevokedUnixSeconds() uint64 {
	if x != nil {
		return x.RevokedUnixSeconds
	}
	return 0
}

func (x *CertificateRevocation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ControllerEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControllerEnvelope_EnrollmentRequest
	//	*ControllerEnvelope_EnrollmentResponse
	//	*ControllerEnvelope_RenewalRequest
	//	*ControllerEnvelope_RenewalResponse
	//	*ControllerEnvelope_ConfigurationRequest
	//	*ControllerEnvelope_NodeConfiguration
	//	*ControllerEnvelope_CertificateRevocation
	//	*ControllerEnvelope_Error
	//	*ControllerEnvelope_RelayConfigurationRequest
	//	*ControllerEnvelope_RelayConfiguration
	//	*ControllerEnvelope_ConfigurationLease
	Body          isControllerEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerEnvelope) Reset() {
	*x = ControllerEnvelope{}
	mi := &file_laneway_v1_controller_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerEnvelope) ProtoMessage() {}

func (x *ControllerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_controller_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerEnvelope.ProtoReflect.Descriptor instead.
func (*ControllerEnvelope) Descriptor() ([]byte, []int) {
	return file_laneway_v1_controller_proto_rawDescGZIP(), []int{17}
}

func (x *ControllerEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ControllerEnvelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ControllerEnvelope) GetBody() isControllerEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControllerEnvelope) GetEnrollmentRequest() *EnrollmentRequest {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_EnrollmentRequest); ok {
			return x.EnrollmentRequest
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetEnrollmentResponse() *EnrollmentResponse {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_EnrollmentResponse); ok {
			return x.EnrollmentResponse
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetRenewalRequest() *RenewalRequest {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_RenewalRequest); ok {
			return x.RenewalRequest
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetRenewalResponse() *RenewalResponse {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_RenewalResponse); ok {
			return x.RenewalResponse
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetConfigurationRequest() *ConfigurationRequest {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_ConfigurationRequest); ok {
			return x.ConfigurationRequest
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetNodeConfiguration() *NodeConfiguration {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_NodeConfiguration); ok {
			return x.NodeConfiguration
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetCertificateRevocation() *CertificateRevocation {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_CertificateRevocation); ok {
			return x.CertificateRevocation
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetRelayConfigurationRequest() *RelayConfigurationRequest {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_RelayConfigurationRequest); ok {
			return x.RelayConfigurationRequest
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetRelayConfiguration() *RelayConfiguration {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_RelayConfiguration); ok {
			return x.RelayConfiguration
		}
	}
	return nil
}

func (x *ControllerEnvelope) GetConfigurationLease() *ConfigurationLease {
	if x != nil {
		if x, ok := x.Body.(*ControllerEnvelope_ConfigurationLease); ok {
			return x.ConfigurationLease
		}
	}
	return nil
}

type isControllerEnvelope_Body interface {
	isControllerEnvelope_Body()
}

type ControllerEnvelope_EnrollmentRequest struct {
	EnrollmentRequest *EnrollmentRequest `protobuf:"bytes,10,opt,name=enrollment_request,json=enrollmentRequest,proto3,oneof"`
}

type ControllerEnvelope_EnrollmentResponse struct {
	EnrollmentResponse *EnrollmentResponse `protobuf:"bytes,11,opt,name=enrollment_response,json=enrollmentResponse,proto3,oneof"`
}

type ControllerEnvelope_RenewalRequest struct {
	RenewalRequest *RenewalRequest `protobuf:"bytes,12,opt,name=renewal_request,json=renewalRequest,proto3,oneof"`
}

type ControllerEnvelope_RenewalResponse struct {
	RenewalResponse *RenewalResponse `protobuf:"bytes,13,opt,name=renewal_response,json=renewalResponse,proto3,oneof"`
}

type ControllerEnvelope_ConfigurationRequest struct {
	ConfigurationRequest *ConfigurationRequest `protobuf:"bytes,14,opt,name=configuration_request,json=configurationRequest,proto3,oneof"`
}

type ControllerEnvelope_NodeConfiguration struct {
	NodeConfiguration *NodeConfiguration `protobuf:"bytes,15,opt,name=node_configuration,json=nodeConfiguration,proto3,oneof"`
}

type ControllerEnvelope_CertificateRevocation struct {
	CertificateRevocation *CertificateRevocation `protobuf:"bytes,16,opt,name=certificate_revocation,json=certificateRevocation,proto3,oneof"`
}

type ControllerEnvelope_Error struct {
	Error *ProtocolError `protobuf:"bytes,17,opt,name=error,proto3,oneof"`
}

type ControllerEnvelope_RelayConfigurationRequest struct {
	RelayConfigurationRequest *RelayConfigurationRequest `protobuf:"bytes,18,opt,name=relay_configuration_request,json=relayConfigurationRequest,proto3,oneof"`
}

type ControllerEnvelope_RelayConfiguration struct {
	RelayConfiguration *RelayConfiguration `protobuf:"bytes,19,opt,name=relay_configuration,json=relayConfiguration,proto3,oneof"`
}

type ControllerEnvelope_ConfigurationLease struct {
	ConfigurationLease *ConfigurationLease `protobuf:"bytes,20,opt,name=configuration_lease,json=configurationLease,proto3,oneof"`
}

func (*ControllerEnvelope_EnrollmentRequest) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_EnrollmentResponse) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_RenewalRequest) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_RenewalResponse) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_ConfigurationRequest) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_NodeConfiguration) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_CertificateRevocation) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_Error) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_RelayConfigurationRequest) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_RelayConfiguration) isControllerEnvelope_Body() {}

func (*ControllerEnvelope_ConfigurationLease) isControllerEnvelope_Body() {}

var File_laneway_v1_controller_proto protoreflect.FileDescriptor

const file_laneway_v1_controller_proto_rawDesc = "" +
	"\n" +
	"\x1blaneway/v1/controller.proto\x12\n" +
	"laneway.v1\x1a\x18laneway/v1/control.proto\x1a\x17laneway/v1/policy.proto\x1a\x17laneway/v1/routes.proto\"\xc6\x02\n" +
	"\x11EnrollmentRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12$\n" +
	"\x0epkcs10_csr_der\x18\x02 \x01(\fR\fpkcs10CsrDer\x12%\n" +
	"\x0erequested_name\x18\x03 \x01(\tR\rrequestedName\x12.\n" +
	"\x13expected_network_id\x18\x04 \x01(\fR\x11expectedNetworkId\x12W\n" +
	"\x19expected_enrollment_class\x18\x05 \x01(\x0e2\x1b.laneway.v1.EnrollmentClassR\x17expectedEnrollmentClass\x120\n" +
	"\x14wireguard_public_key\x18\x06 \x01(\fR\x12wireguardPublicKey\"r\n" +
	"\x10CertificateChain\x12)\n" +
	"\x10certificates_der\x18\x01 \x03(\fR\x0fcertificatesDer\x123\n" +
	"\x16not_after_unix_seconds\x18\x02 \x01(\x04R\x13notAfterUnixSeconds\"\x80\x03\n" +
	"\x12EnrollmentResponse\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12I\n" +
	"\x11certificate_chain\x18\x03 \x01(\v2\x1c.laneway.v1.CertificateChainR\x10certificateChain\x12+\n" +
	"\x11overlay_addresses\x18\x04 \x03(\fR\x10overlayAddresses\x12F\n" +
	"\x10enrollment_class\x18\x05 \x01(\x0e2\x1b.laneway.v1.EnrollmentClassR\x0fenrollmentClass\x12@\n" +
	"\x1dlease_expires_at_unix_seconds\x18\x06 \x01(\x04R\x19leaseExpiresAtUnixSeconds\x120\n" +
	"\x14wireguard_public_key\x18\a \x01(\fR\x12wireguardPublicKey\"h\n" +
	"\x0eRenewalRequest\x12$\n" +
	"\x0epkcs10_csr_der\x18\x01 \x01(\fR\fpkcs10CsrDer\x120\n" +
	"\x14wireguard_public_key\x18\x02 \x01(\fR\x12wireguardPublicKey\"\x8e\x01\n" +
	"\x0fRenewalResponse\x12I\n" +
	"\x11certificate_chain\x18\x01 \x01(\v2\x1c.laneway.v1.CertificateChainR\x10certificateChain\x120\n" +
	"\x14wireguard_public_key\x18\x02 \x01(\fR\x12wireguardPublicKey\"\xdd\x06\n" +
	"\x11NodeConfiguration\x12/\n" +
	"\x13configuration_epoch\x18\x01 \x01(\x04R\x12configurationEpoch\x12+\n" +
	"\x11overlay_addresses\x18\x02 \x03(\fR\x10overlayAddresses\x121\n" +
	"\x06routes\x18\x03 \x01(\v2\x19.laneway.v1.RouteSnapshotR\x06routes\x122\n" +
	"\x06policy\x18\x04 \x01(\v2\x1a.laneway.v1.PolicySnapshotR\x06policy\x121\n" +
	"\x14enabled_capabilities\x18\x05 \x01(\x04R\x13enabledCapabilities\x127\n" +
	"\x18valid_until_unix_seconds\x18\x06 \x01(\x04R\x15validUntilUnixSeconds\x12>\n" +
	"\x1brevoked_certificate_serials\x18\a \x03(\fR\x19revokedCertificateSerials\x12*\n" +
	"\x05peers\x18\b \x03(\v2\x14.laneway.v1.NodePeerR\x05peers\x121\n" +
	"\x06relays\x18\t \x03(\v2\x19.laneway.v1.RelayEndpointR\x06relays\x12R\n" +
	"\x12candidate_exchange\x18\n" +
	" \x01(\v2#.laneway.v1.CandidateExchangePolicyR\x11candidateExchange\x12;\n" +
	"\vexit_policy\x18\v \x01(\v2\x1a.laneway.v1.ExitNodePolicyR\n" +
	"exitPolicy\x12L\n" +
	"\x12certificate_health\x18\f \x01(\v2\x1d.laneway.v1.CertificateHealthR\x11certificateHealth\x12F\n" +
	"\x10enrollment_class\x18\r \x01(\x0e2\x1b.laneway.v1.EnrollmentClassR\x0fenrollmentClass\x12Q\n" +
	"&identity_lease_expires_at_unix_seconds\x18\x0e \x01(\x04R!identityLeaseExpiresAtUnixSeconds\"\x96\x01\n" +
	"\bNodePeer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x11overlay_addresses\x18\x03 \x03(\fR\x10overlayAddresses\x120\n" +
	"\x14wireguard_public_key\x18\x04 \x01(\fR\x12wireguardPublicKey\"^\n" +
	"\rRelayEndpoint\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\fR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"\x8e\x01\n" +
	"\x17CandidateExchangePolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12%\n" +
	"\x0emax_candidates\x18\x02 \x01(\rR\rmaxCandidates\x122\n" +
	"\x15candidate_ttl_seconds\x18\x03 \x01(\rR\x13candidateTtlSeconds\"@\n" +
	"\x0eExitNodePolicy\x12.\n" +
	"\x13authorized_node_ids\x18\x01 \x03(\fR\x11authorizedNodeIds\"\xc6\x01\n" +
	"\x11CertificateHealth\x12)\n" +
	"\x10presented_serial\x18\x01 \x01(\fR\x0fpresentedSerial\x123\n" +
	"\x16not_after_unix_seconds\x18\x02 \x01(\x04R\x13notAfterUnixSeconds\x127\n" +
	"\x18renew_after_unix_seconds\x18\x03 \x01(\x04R\x15renewAfterUnixSeconds\x12\x18\n" +
	"\arevoked\x18\x04 \x01(\bR\arevoked\"R\n" +
	"\x14ConfigurationRequest\x12:\n" +
	"\x19known_configuration_epoch\x18\x01 \x01(\x04R\x17knownConfigurationEpoch\"W\n" +
	"\x19RelayConfigurationRequest\x12:\n" +
	"\x19known_configuration_epoch\x18\x01 \x01(\x04R\x17knownConfigurationEpoch\"\xa5\x01\n" +
	"\x16RelayPeerAuthorization\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12+\n" +
	"\x11overlay_addresses\x18\x02 \x03(\fR\x10overlayAddresses\x12E\n" +
	"\x13authorized_prefixes\x18\x03 \x03(\v2\x14.laneway.v1.IpPrefixR\x12authorizedPrefixes\"\x99\x03\n" +
	"\x12RelayConfiguration\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\x12/\n" +
	"\x13configuration_epoch\x18\x02 \x01(\x04R\x12configurationEpoch\x128\n" +
	"\x05peers\x18\x03 \x03(\v2\".laneway.v1.RelayPeerAuthorizationR\x05peers\x122\n" +
	"\x06policy\x18\x04 \x01(\v2\x1a.laneway.v1.PolicySnapshotR\x06policy\x127\n" +
	"\x18valid_until_unix_seconds\x18\x05 \x01(\x04R\x15validUntilUnixSeconds\x12>\n" +
	"\x1brevoked_certificate_serials\x18\x06 \x03(\fR\x19revokedCertificateSerials\x12L\n" +
	"\x12certificate_health\x18\a \x01(\v2\x1d.laneway.v1.CertificateHealthR\x11certificateHealth\"~\n" +
	"\x12ConfigurationLease\x12/\n" +
	"\x13configuration_epoch\x18\x01 \x01(\x04R\x12configurationEpoch\x127\n" +
	"\x18valid_until_unix_seconds\x18\x02 \x01(\x04R\x15validUntilUnixSeconds\"\xa9\x01\n" +
	"\x15CertificateRevocation\x12-\n" +
	"\x12certificate_serial\x18\x01 \x01(\fR\x11certificateSerial\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x120\n" +
	"\x14revoked_unix_seconds\x18\x03 \x01(\x04R\x12revokedUnixSeconds\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xdd\a\n" +
	"\x12ControllerEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12N\n" +
	"\x12enrollment_request\x18\n" +
	" \x01(\v2\x1d.laneway.v1.EnrollmentRequestH\x00R\x11enrollmentRequest\x12Q\n" +
	"\x13enrollment_response\x18\v \x01(\v2\x1e.laneway.v1.EnrollmentResponseH\x00R\x12enrollmentResponse\x12E\n" +
	"\x0frenewal_request\x18\f \x01(\v2\x1a.laneway.v1.RenewalRequestH\x00R\x0erenewalRequest\x12H\n" +
	"\x10renewal_response\x18\r \x01(\v2\x1b.laneway.v1.RenewalResponseH\x00R\x0frenewalResponse\x12W\n" +
	"\x15configuration_request\x18\x0e \x01(\v2 .laneway.v1.ConfigurationRequestH\x00R\x14configurationRequest\x12N\n" +
	"\x12node_configuration\x18\x0f \x01(\v2\x1d.laneway.v1.NodeConfigurationH\x00R\x11nodeConfiguration\x12Z\n" +
	"\x16certificate_revocation\x18\x10 \x01(\v2!.laneway.v1.CertificateRevocationH\x00R\x15certificateRevocation\x121\n" +
	"\x05error\x18\x11 \x01(\v2\x19.laneway.v1.ProtocolErrorH\x00R\x05error\x12g\n" +
	"\x1brelay_configuration_request\x18\x12 \x01(\v2%.laneway.v1.RelayConfigurationRequestH\x00R\x19relayConfigurationRequest\x12Q\n" +
	"\x13relay_configuration\x18\x13 \x01(\v2\x1e.laneway.v1.RelayConfigurationH\x00R\x12relayConfiguration\x12Q\n" +
	"\x13configuration_lease\x18\x14 \x01(\v2\x1e.laneway.v1.ConfigurationLeaseH\x00R\x12configurationLeaseB\x06\n" +
	"\x04body*\xa1\x01\n" +
	"\x0fEnrollmentClass\x12 \n" +
	"\x1cENROLLMENT_CLASS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dENROLLMENT_CLASS_DURABLE_NODE\x10\x01\x12#\n" +
	"\x1fENROLLMENT_CLASS_EPHEMERAL_USER\x10\x02\x12$\n" +
	" ENROLLMENT_CLASS_REMEMBERED_USER\x10\x03B.Z,laneway.dev/laneway/api/laneway/v1;lanewayv1b\x06proto3"

var (
	file_laneway_v1_controller_proto_rawDescOnce sync.Once
	file_laneway_v1_controller_proto_rawDescData []byte
)

func file_laneway_v1_controller_proto_rawDescGZIP() []byte {
	file_laneway_v1_controller_proto_rawDescOnce.Do(func() {
		file_laneway_v1_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laneway_v1_controller_proto_rawDesc), len(file_laneway_v1_controller_proto_rawDesc)))
	})
	return file_laneway_v1_controller_proto_rawDescData
}

var file_laneway_v1_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_laneway_v1_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_laneway_v1_controller_proto_goTypes = []any{
	(EnrollmentClass)(0),              // 0: laneway.v1.EnrollmentClass
	(*EnrollmentRequest)(nil),         // 1: laneway.v1.EnrollmentRequest
	(*CertificateChain)(nil),          // 2: laneway.v1.CertificateChain
	(*EnrollmentResponse)(nil),        // 3: laneway.v1.EnrollmentResponse
	(*RenewalRequest)(nil),            // 4: laneway.v1.RenewalRequest
	(*RenewalResponse)(nil),           // 5: laneway.v1.RenewalResponse
	(*NodeConfiguration)(nil),         // 6: laneway.v1.NodeConfiguration
	(*NodePeer)(nil),                  // 7: laneway.v1.NodePeer
	(*RelayEndpoint)(nil),             // 8: laneway.v1.RelayEndpoint
	(*CandidateExchangePolicy)(nil),   // 9: laneway.v1.CandidateExchangePolicy
	(*ExitNodePolicy)(nil),            // 10: laneway.v1.ExitNodePolicy
	(*CertificateHealth)(nil),         // 11: laneway.v1.CertificateHealth
	(*ConfigurationRequest)(nil),      // 12: laneway.v1.ConfigurationRequest
	(*RelayConfigurationRequest)(nil), // 13: laneway.v1.RelayConfigurationRequest
	(*RelayPeerAuthorization)(nil),    // 14: laneway.v1.RelayPeerAuthorization
	(*RelayConfiguration)(nil),        // 15: laneway.v1.RelayConfiguration
	(*ConfigurationLease)(nil),        // 16: laneway.v1.ConfigurationLease
	(*CertificateRevocation)(nil),     // 17: laneway.v1.CertificateRevocation
	(*ControllerEnvelope)(nil),        // 18: laneway.v1.ControllerEnvelope
	(*RouteSnapshot)(nil),             // 19: laneway.v1.RouteSnapshot
	(*PolicySnapshot)(nil),            // 20: laneway.v1.PolicySnapshot
	(*IpPrefix)(nil),                  // 21: laneway.v1.IpPrefix
	(*ProtocolError)(nil),             // 22: laneway.v1.ProtocolError
}
var file_laneway_v1_controller_proto_depIdxs = []int32{
	0,  // 0: laneway.v1.EnrollmentRequest.expected_enrollment_class:type_name -> laneway.v1.EnrollmentClass
	2,  // 1: laneway.v1.EnrollmentResponse.certificate_chain:type_name -> laneway.v1.CertificateChain
	0,  // 2: laneway.v1.EnrollmentResponse.enrollment_class:type_name -> laneway.v1.EnrollmentClass
	2,  // 3: laneway.v1.RenewalResponse.certificate_chain:type_name -> laneway.v1.CertificateChain
	19, // 4: laneway.v1.NodeConfiguration.routes:type_name -> laneway.v1.RouteSnapshot
	20, // 5: laneway.v1.NodeConfiguration.policy:type_name -> laneway.v1.PolicySnapshot
	7,  // 6: laneway.v1.NodeConfiguration.peers:type_name -> laneway.v1.NodePeer
	8,  // 7: laneway.v1.NodeConfiguration.relays:type_name -> laneway.v1.RelayEndpoint
	9,  // 8: laneway.v1.NodeConfiguration.candidate_exchange:type_name -> laneway.v1.CandidateExchangePolicy
	10, // 9: laneway.v1.NodeConfiguration.exit_policy:type_name -> laneway.v1.ExitNodePolicy
	11, // 10: laneway.v1.NodeConfiguration.certificate_health:type_name -> laneway.v1.CertificateHealth
	0,  // 11: laneway.v1.NodeConfiguration.enrollment_class:type_name -> laneway.v1.EnrollmentClass
	21, // 12: laneway.v1.RelayPeerAuthorization.authorized_prefixes:type_name -> laneway.v1.IpPrefix
	14, // 13: laneway.v1.RelayConfiguration.peers:type_name -> laneway.v1.RelayPeerAuthorization
	20, // 14: laneway.v1.RelayConfiguration.policy:type_name -> laneway.v1.PolicySnapshot
	11, // 15: laneway.v1.RelayConfiguration.certificate_health:type_name -> laneway.v1.CertificateHealth
	1,  // 16: laneway.v1.ControllerEnvelope.enrollment_request:type_name -> laneway.v1.EnrollmentRequest
	3,  // 17: laneway.v1.ControllerEnvelope.enrollment_response:type_name -> laneway.v1.EnrollmentResponse
	4,  // 18: laneway.v1.ControllerEnvelope.renewal_request:type_name -> laneway.v1.RenewalRequest
	5,  // 19: laneway.v1.ControllerEnvelope.renewal_response:type_name -> laneway.v1.RenewalResponse
	12, // 20: laneway.v1.ControllerEnvelope.configuration_request:type_name -> laneway.v1.ConfigurationRequest
	6,  // 21: laneway.v1.ControllerEnvelope.node_configuration:type_name -> laneway.v1.NodeConfiguration
	17, // 22: laneway.v1.ControllerEnvelope.certificate_revocation:type_name -> laneway.v1.CertificateRevocation
	22, // 23: laneway.v1.ControllerEnvelope.error:type_name -> laneway.v1.ProtocolError
	13, // 24: laneway.v1.ControllerEnvelope.relay_configuration_request:type_name -> laneway.v1.RelayConfigurationRequest
	15, // 25: laneway.v1.ControllerEnvelope.relay_configuration:type_name -> laneway.v1.RelayConfiguration
	16, // 26: laneway.v1.ControllerEnvelope.configuration_lease:type_name -> laneway.v1.ConfigurationLease
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_laneway_v1_controller_proto_init() }
func file_laneway_v1_controller_proto_init() {
	if File_laneway_v1_controller_proto != nil {
		return
	}
	file_laneway_v1_control_proto_init()
	file_laneway_v1_policy_proto_init()
	file_laneway_v1_routes_proto_init()
	file_laneway_v1_controller_proto_msgTypes[17].OneofWrappers = []any{
		(*ControllerEnvelope_EnrollmentRequest)(nil),
		(*ControllerEnvelope_EnrollmentResponse)(nil),
		(*ControllerEnvelope_RenewalRequest)(nil),
		(*ControllerEnvelope_RenewalResponse)(nil),
		(*ControllerEnvelope_ConfigurationRequest)(nil),
		(*ControllerEnvelope_NodeConfiguration)(nil),
		(*ControllerEnvelope_CertificateRevocation)(nil),
		(*ControllerEnvelope_Error)(nil),
		(*ControllerEnvelope_RelayConfigurationRequest)(nil),
		(*ControllerEnvelope_RelayConfiguration)(nil),
		(*ControllerEnvelope_ConfigurationLease)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laneway_v1_controller_proto_rawDesc), len(file_laneway_v1_controller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laneway_v1_controller_proto_goTypes,
		DependencyIndexes: file_laneway_v1_controller_proto_depIdxs,
		EnumInfos:         file_laneway_v1_controller_proto_enumTypes,
		MessageInfos:      file_laneway_v1_controller_proto_msgTypes,
	}.Build()
	File_laneway_v1_controller_proto = out.File
	file_laneway_v1_controller_proto_goTypes = nil
	file_laneway_v1_controller_proto_depIdxs = nil
}
