// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: laneway/v1/control.proto

package lanewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capability values are bit masks carried in uint64 capability fields.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED              Capability = 0
	Capability_CAPABILITY_LANEWAY_RELAY_V1         Capability = 1
	Capability_CAPABILITY_LANEWAY_QUIC_DATAGRAM_V1 Capability = 2
	Capability_CAPABILITY_LANEWAY_DIRECT_PEER_V1   Capability = 4
	Capability_CAPABILITY_LANEWAY_SUBNET_ROUTER_V1 Capability = 8
	Capability_CAPABILITY_LANEWAY_EXIT_NODE_V1     Capability = 16
	Capability_CAPABILITY_LANEWAY_TCP_FALLBACK_V1  Capability = 32
	Capability_CAPABILITY_LANEWAY_IPV6_V1          Capability = 64
	Capability_CAPABILITY_LANEWAY_E2E_PACKET_V1    Capability = 128
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0:   "CAPABILITY_UNSPECIFIED",
		1:   "CAPABILITY_LANEWAY_RELAY_V1",
		2:   "CAPABILITY_LANEWAY_QUIC_DATAGRAM_V1",
		4:   "CAPABILITY_LANEWAY_DIRECT_PEER_V1",
		8:   "CAPABILITY_LANEWAY_SUBNET_ROUTER_V1",
		16:  "CAPABILITY_LANEWAY_EXIT_NODE_V1",
		32:  "CAPABILITY_LANEWAY_TCP_FALLBACK_V1",
		64:  "CAPABILITY_LANEWAY_IPV6_V1",
		128: "CAPABILITY_LANEWAY_E2E_PACKET_V1",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":              0,
		"CAPABILITY_LANEWAY_RELAY_V1":         1,
		"CAPABILITY_LANEWAY_QUIC_DATAGRAM_V1": 2,
		"CAPABILITY_LANEWAY_DIRECT_PEER_V1":   4,
		"CAPABILITY_LANEWAY_SUBNET_ROUTER_V1": 8,
		"CAPABILITY_LANEWAY_EXIT_NODE_V1":     16,
		"CAPABILITY_LANEWAY_TCP_FALLBACK_V1":  32,
		"CAPABILITY_LANEWAY_IPV6_V1":          64,
		"CAPABILITY_LANEWAY_E2E_PACKET_V1":    128,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_control_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_laneway_v1_control_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ErrorCode_ERROR_CODE_MALFORMED           ErrorCode = 1
	ErrorCode_ERROR_CODE_UNSUPPORTED_VERSION ErrorCode = 2
	ErrorCode_ERROR_CODE_UNAUTHENTICATED     ErrorCode = 3
	ErrorCode_ERROR_CODE_PERMISSION_DENIED   ErrorCode = 4
	ErrorCode_ERROR_CODE_STALE_EPOCH         ErrorCode = 5
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED  ErrorCode = 6
	ErrorCode_ERROR_CODE_INTERNAL            ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_MALFORMED",
		2: "ERROR_CODE_UNSUPPORTED_VERSION",
		3: "ERROR_CODE_UNAUTHENTICATED",
		4: "ERROR_CODE_PERMISSION_DENIED",
		5: "ERROR_CODE_STALE_EPOCH",
		6: "ERROR_CODE_RESOURCE_EXHAUSTED",
		7: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_MALFORMED":           1,
		"ERROR_CODE_UNSUPPORTED_VERSION": 2,
		"ERROR_CODE_UNAUTHENTICATED":     3,
		"ERROR_CODE_PERMISSION_DENIED":   4,
		"ERROR_CODE_STALE_EPOCH":         5,
		"ERROR_CODE_RESOURCE_EXHAUSTED":  6,
		"ERROR_CODE_INTERNAL":            7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_control_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_laneway_v1_control_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{1}
}

// Opaque identifiers are exactly 16 bytes. Receivers MUST reject other sizes.
type NetworkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     []byte                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRef) Reset() {
	*x = NetworkRef{}
	mi := &file_laneway_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRef) ProtoMessage() {}

func (x *NetworkRef) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRef.ProtoReflect.Descriptor instead.
func (*NetworkRef) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkRef) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

type NodeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     []byte                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRef) Reset() {
	*x = NodeRef{}
	mi := &file_laneway_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRef) ProtoMessage() {}

func (x *NodeRef) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRef.ProtoReflect.Descriptor instead.
func (*NodeRef) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRef) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *NodeRef) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     []byte                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BootId        []byte                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ProtocolMajor uint32                 `protobuf:"varint,4,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ProtocolMinor uint32                 `protobuf:"varint,5,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	Capabilities  uint64                 `protobuf:"varint,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_laneway_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *Hello) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Hello) GetBootId() []byte {
	if x != nil {
		return x.BootId
	}
	return nil
}

func (x *Hello) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *Hello) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *Hello) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

type Welcome struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConfigurationEpoch uint64                 `protobuf:"varint,2,opt,name=configuration_epoch,json=configurationEpoch,proto3" json:"configuration_epoch,omitempty"`
	// Network-order IPv4 (4 bytes) or IPv6 (16 bytes), never text.
	OverlayAddresses  [][]byte `protobuf:"bytes,3,rep,name=overlay_addresses,json=overlayAddresses,proto3" json:"overlay_addresses,omitempty"`
	Capabilities      uint64   `protobuf:"varint,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxControlPayload uint32   `protobuf:"varint,5,opt,name=max_control_payload,json=maxControlPayload,proto3" json:"max_control_payload,omitempty"`
	MaxPacketPayload  uint32   `protobuf:"varint,6,opt,name=max_packet_payload,json=maxPacketPayload,proto3" json:"max_packet_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_laneway_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *Welcome) GetConfigurationEpoch() uint64 {
	if x != nil {
		return x.ConfigurationEpoch
	}
	return 0
}

func (x *Welcome) GetOverlayAddresses() [][]byte {
	if x != nil {
		return x.OverlayAddresses
	}
	return nil
}

func (x *Welcome) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *Welcome) GetMaxControlPayload() uint32 {
	if x != nil {
		return x.MaxControlPayload
	}
	return 0
}

func (x *Welcome) GetMaxPacketPayload() uint32 {
	if x != nil {
		return x.MaxPacketPayload
	}
	return 0
}

type Ping struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nonce          uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	SentUnixMillis uint64                 `protobuf:"varint,2,opt,name=sent_unix_millis,json=sentUnixMillis,proto3" json:"sent_unix_millis,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_laneway_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Ping) GetSentUnixMillis() uint64 {
	if x != nil {
		return x.SentUnixMillis
	}
	return 0
}

type Pong struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Nonce              uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ReceivedUnixMillis uint64                 `protobuf:"varint,2,opt,name=received_unix_millis,json=receivedUnixMillis,proto3" json:"received_unix_millis,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_laneway_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Pong) GetReceivedUnixMillis() uint64 {
	if x != nil {
		return x.ReceivedUnixMillis
	}
	return 0
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=laneway.v1.ErrorCode" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_laneway_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ProtocolError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ProtocolError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ProtocolError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type ConfigurationAck struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConfigurationEpoch uint64                 `protobuf:"varint,1,opt,name=configuration_epoch,json=configurationEpoch,proto3" json:"configuration_epoch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigurationAck) Reset() {
	*x = ConfigurationAck{}
	mi := &file_laneway_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationAck) ProtoMessage() {}

func (x *ConfigurationAck) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationAck.ProtoReflect.Descriptor instead.
func (*ConfigurationAck) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigurationAck) GetConfigurationEpoch() uint64 {
	if x != nil {
		return x.ConfigurationEpoch
	}
	return 0
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        ErrorCode              `protobuf:"varint,1,opt,name=reason,proto3,enum=laneway.v1.ErrorCode" json:"reason,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_laneway_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *Disconnect) GetReason() ErrorCode {
	if x != nil {
		return x.Reason
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Disconnect) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// ControlEnvelope is the payload of a 4-byte, big-endian length-prefixed frame.
// schema_version is 1 for this package. Exactly one body member must be set.
type ControlEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControlEnvelope_Hello
	//	*ControlEnvelope_Welcome
	//	*ControlEnvelope_Ping
	//	*ControlEnvelope_Pong
	//	*ControlEnvelope_Error
	//	*ControlEnvelope_ConfigurationAck
	//	*ControlEnvelope_Disconnect
	Body          isControlEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEnvelope) Reset() {
	*x = ControlEnvelope{}
	mi := &file_laneway_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEnvelope) ProtoMessage() {}

func (x *ControlEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEnvelope.ProtoReflect.Descriptor instead.
func (*ControlEnvelope) Descriptor() ([]byte, []int) {
	return file_laneway_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ControlEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ControlEnvelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControlEnvelope) GetBody() isControlEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlEnvelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControlEnvelope) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControlEnvelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ControlEnvelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ControlEnvelope) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ControlEnvelope) GetConfigurationAck() *ConfigurationAck {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_ConfigurationAck); ok {
			return x.ConfigurationAck
		}
	}
	return nil
}

func (x *ControlEnvelope) GetDisconnect() *Disconnect {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isControlEnvelope_Body interface {
	isControlEnvelope_Body()
}

type ControlEnvelope_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type ControlEnvelope_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,11,opt,name=welcome,proto3,oneof"`
}

type ControlEnvelope_Ping struct {
	Ping *Ping `protobuf:"bytes,12,opt,name=ping,proto3,oneof"`
}

type ControlEnvelope_Pong struct {
	Pong *Pong `protobuf:"bytes,13,opt,name=pong,proto3,oneof"`
}

type ControlEnvelope_Error struct {
	Error *ProtocolError `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

type ControlEnvelope_ConfigurationAck struct {
	ConfigurationAck *ConfigurationAck `protobuf:"bytes,15,opt,name=configuration_ack,json=configurationAck,proto3,oneof"`
}

type ControlEnvelope_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,16,opt,name=disconnect,proto3,oneof"`
}

func (*ControlEnvelope_Hello) isControlEnvelope_Body() {}

func (*ControlEnvelope_Welcome) isControlEnvelope_Body() {}

func (*ControlEnvelope_Ping) isControlEnvelope_Body() {}

func (*ControlEnvelope_Pong) isControlEnvelope_Body() {}

func (*ControlEnvelope_Error) isControlEnvelope_Body() {}

func (*ControlEnvelope_ConfigurationAck) isControlEnvelope_Body() {}

func (*ControlEnvelope_Disconnect) isControlEnvelope_Body() {}

var File_laneway_v1_control_proto protoreflect.FileDescriptor

const file_laneway_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18laneway/v1/control.proto\x12\n" +
	"laneway.v1\"+\n" +
	"\n" +
	"NetworkRef\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\"A\n" +
	"\aNodeRef\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\"\xca\x01\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\fR\x06bootId\x12%\n" +
	"\x0eprotocol_major\x18\x04 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0eprotocol_minor\x18\x05 \x01(\rR\rprotocolMinor\x12\"\n" +
	"\fcapabilities\x18\x06 \x01(\x04R\fcapabilities\"\x88\x02\n" +
	"\aWelcome\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12/\n" +
	"\x13configuration_epoch\x18\x02 \x01(\x04R\x12configurationEpoch\x12+\n" +
	"\x11overlay_addresses\x18\x03 \x03(\fR\x10overlayAddresses\x12\"\n" +
	"\fcapabilities\x18\x04 \x01(\x04R\fcapabilities\x12.\n" +
	"\x13max_control_payload\x18\x05 \x01(\rR\x11maxControlPayload\x12,\n" +
	"\x12max_packet_payload\x18\x06 \x01(\rR\x10maxPacketPayload\"F\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12(\n" +
	"\x10sent_unix_millis\x18\x02 \x01(\x04R\x0esentUnixMillis\"N\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x120\n" +
	"\x14received_unix_millis\x18\x02 \x01(\x04R\x12receivedUnixMillis\"p\n" +
	"\rProtocolError\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.laneway.v1.ErrorCodeR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"C\n" +
	"\x10ConfigurationAck\x12/\n" +
	"\x13configuration_epoch\x18\x01 \x01(\x04R\x12configurationEpoch\"S\n" +
	"\n" +
	"Disconnect\x12-\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x15.laneway.v1.ErrorCodeR\x06reason\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xc2\x03\n" +
	"\x0fControlEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12)\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x11.laneway.v1.HelloH\x00R\x05hello\x12/\n" +
	"\awelcome\x18\v \x01(\v2\x13.laneway.v1.WelcomeH\x00R\awelcome\x12&\n" +
	"\x04ping\x18\f \x01(\v2\x10.laneway.v1.PingH\x00R\x04ping\x12&\n" +
	"\x04pong\x18\r \x01(\v2\x10.laneway.v1.PongH\x00R\x04pong\x121\n" +
	"\x05error\x18\x0e \x01(\v2\x19.laneway.v1.ProtocolErrorH\x00R\x05error\x12K\n" +
	"\x11configuration_ack\x18\x0f \x01(\v2\x1c.laneway.v1.ConfigurationAckH\x00R\x10configurationAck\x128\n" +
	"\n" +
	"disconnect\x18\x10 \x01(\v2\x16.laneway.v1.DisconnectH\x00R\n" +
	"disconnectB\x06\n" +
	"\x04body*\xd6\x02\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCAPABILITY_LANEWAY_RELAY_V1\x10\x01\x12'\n" +
	"#CAPABILITY_LANEWAY_QUIC_DATAGRAM_V1\x10\x02\x12%\n" +
	"!CAPABILITY_LANEWAY_DIRECT_PEER_V1\x10\x04\x12'\n" +
	"#CAPABILITY_LANEWAY_SUBNET_ROUTER_V1\x10\b\x12#\n" +
	"\x1fCAPABILITY_LANEWAY_EXIT_NODE_V1\x10\x10\x12&\n" +
	"\"CAPABILITY_LANEWAY_TCP_FALLBACK_V1\x10 \x12\x1e\n" +
	"\x1aCAPABILITY_LANEWAY_IPV6_V1\x10@\x12%\n" +
	" CAPABILITY_LANEWAY_E2E_PACKET_V1\x10\x80\x01*\xff\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ERROR_CODE_MALFORMED\x10\x01\x12\"\n" +
	"\x1eERROR_CODE_UNSUPPORTED_VERSION\x10\x02\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x03\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x04\x12\x1a\n" +
	"\x16ERROR_CODE_STALE_EPOCH\x10\x05\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\x06\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\aB6Z4github.com/Doout/laneway/go/api/laneway/v1;lanewayv1b\x06proto3"

var (
	file_laneway_v1_control_proto_rawDescOnce sync.Once
	file_laneway_v1_control_proto_rawDescData []byte
)

func file_laneway_v1_control_proto_rawDescGZIP() []byte {
	file_laneway_v1_control_proto_rawDescOnce.Do(func() {
		file_laneway_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laneway_v1_control_proto_rawDesc), len(file_laneway_v1_control_proto_rawDesc)))
	})
	return file_laneway_v1_control_proto_rawDescData
}

var file_laneway_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_laneway_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_laneway_v1_control_proto_goTypes = []any{
	(Capability)(0),          // 0: laneway.v1.Capability
	(ErrorCode)(0),           // 1: laneway.v1.ErrorCode
	(*NetworkRef)(nil),       // 2: laneway.v1.NetworkRef
	(*NodeRef)(nil),          // 3: laneway.v1.NodeRef
	(*Hello)(nil),            // 4: laneway.v1.Hello
	(*Welcome)(nil),          // 5: laneway.v1.Welcome
	(*Ping)(nil),             // 6: laneway.v1.Ping
	(*Pong)(nil),             // 7: laneway.v1.Pong
	(*ProtocolError)(nil),    // 8: laneway.v1.ProtocolError
	(*ConfigurationAck)(nil), // 9: laneway.v1.ConfigurationAck
	(*Disconnect)(nil),       // 10: laneway.v1.Disconnect
	(*ControlEnvelope)(nil),  // 11: laneway.v1.ControlEnvelope
}
var file_laneway_v1_control_proto_depIdxs = []int32{
	1,  // 0: laneway.v1.ProtocolError.code:type_name -> laneway.v1.ErrorCode
	1,  // 1: laneway.v1.Disconnect.reason:type_name -> laneway.v1.ErrorCode
	4,  // 2: laneway.v1.ControlEnvelope.hello:type_name -> laneway.v1.Hello
	5,  // 3: laneway.v1.ControlEnvelope.welcome:type_name -> laneway.v1.Welcome
	6,  // 4: laneway.v1.ControlEnvelope.ping:type_name -> laneway.v1.Ping
	7,  // 5: laneway.v1.ControlEnvelope.pong:type_name -> laneway.v1.Pong
	8,  // 6: laneway.v1.ControlEnvelope.error:type_name -> laneway.v1.ProtocolError
	9,  // 7: laneway.v1.ControlEnvelope.configuration_ack:type_name -> laneway.v1.ConfigurationAck
	10, // 8: laneway.v1.ControlEnvelope.disconnect:type_name -> laneway.v1.Disconnect
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_laneway_v1_control_proto_init() }
func file_laneway_v1_control_proto_init() {
	if File_laneway_v1_control_proto != nil {
		return
	}
	file_laneway_v1_control_proto_msgTypes[9].OneofWrappers = []any{
		(*ControlEnvelope_Hello)(nil),
		(*ControlEnvelope_Welcome)(nil),
		(*ControlEnvelope_Ping)(nil),
		(*ControlEnvelope_Pong)(nil),
		(*ControlEnvelope_Error)(nil),
		(*ControlEnvelope_ConfigurationAck)(nil),
		(*ControlEnvelope_Disconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laneway_v1_control_proto_rawDesc), len(file_laneway_v1_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laneway_v1_control_proto_goTypes,
		DependencyIndexes: file_laneway_v1_control_proto_depIdxs,
		EnumInfos:         file_laneway_v1_control_proto_enumTypes,
		MessageInfos:      file_laneway_v1_control_proto_msgTypes,
	}.Build()
	File_laneway_v1_control_proto = out.File
	file_laneway_v1_control_proto_goTypes = nil
	file_laneway_v1_control_proto_depIdxs = nil
}
