// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: laneway/v1/policy.proto

package lanewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyAction int32

const (
	PolicyAction_POLICY_ACTION_UNSPECIFIED PolicyAction = 0
	PolicyAction_POLICY_ACTION_ACCEPT      PolicyAction = 1
	PolicyAction_POLICY_ACTION_DENY        PolicyAction = 2
)

// Enum value maps for PolicyAction.
var (
	PolicyAction_name = map[int32]string{
		0: "POLICY_ACTION_UNSPECIFIED",
		1: "POLICY_ACTION_ACCEPT",
		2: "POLICY_ACTION_DENY",
	}
	PolicyAction_value = map[string]int32{
		"POLICY_ACTION_UNSPECIFIED": 0,
		"POLICY_ACTION_ACCEPT":      1,
		"POLICY_ACTION_DENY":        2,
	}
)

func (x PolicyAction) Enum() *PolicyAction {
	p := new(PolicyAction)
	*p = x
	return p
}

func (x PolicyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_policy_proto_enumTypes[0].Descriptor()
}

func (PolicyAction) Type() protoreflect.EnumType {
	return &file_laneway_v1_policy_proto_enumTypes[0]
}

func (x PolicyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyAction.Descriptor instead.
func (PolicyAction) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_policy_proto_rawDescGZIP(), []int{0}
}

type IpProtocol int32

const (
	IpProtocol_IP_PROTOCOL_UNSPECIFIED IpProtocol = 0
	IpProtocol_IP_PROTOCOL_ICMP        IpProtocol = 1
	IpProtocol_IP_PROTOCOL_TCP         IpProtocol = 6
	IpProtocol_IP_PROTOCOL_UDP         IpProtocol = 17
	IpProtocol_IP_PROTOCOL_ICMPV6      IpProtocol = 58
	// ANY is deliberately nonzero so an omitted field cannot broaden policy.
	IpProtocol_IP_PROTOCOL_ANY IpProtocol = 256
)

// Enum value maps for IpProtocol.
var (
	IpProtocol_name = map[int32]string{
		0:   "IP_PROTOCOL_UNSPECIFIED",
		1:   "IP_PROTOCOL_ICMP",
		6:   "IP_PROTOCOL_TCP",
		17:  "IP_PROTOCOL_UDP",
		58:  "IP_PROTOCOL_ICMPV6",
		256: "IP_PROTOCOL_ANY",
	}
	IpProtocol_value = map[string]int32{
		"IP_PROTOCOL_UNSPECIFIED": 0,
		"IP_PROTOCOL_ICMP":        1,
		"IP_PROTOCOL_TCP":         6,
		"IP_PROTOCOL_UDP":         17,
		"IP_PROTOCOL_ICMPV6":      58,
		"IP_PROTOCOL_ANY":         256,
	}
)

func (x IpProtocol) Enum() *IpProtocol {
	p := new(IpProtocol)
	*p = x
	return p
}

func (x IpProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_policy_proto_enumTypes[1].Descriptor()
}

func (IpProtocol) Type() protoreflect.EnumType {
	return &file_laneway_v1_policy_proto_enumTypes[1]
}

func (x IpProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpProtocol.Descriptor instead.
func (IpProtocol) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_policy_proto_rawDescGZIP(), []int{1}
}

type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         uint32                 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last          uint32                 `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_laneway_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_laneway_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PortRange) GetFirst() uint32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *PortRange) GetLast() uint32 {
	if x != nil {
		return x.Last
	}
	return 0
}

type TrafficSelector struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeIds       [][]byte               `protobuf:"bytes,1,rep,name=source_node_ids,json=sourceNodeIds,proto3" json:"source_node_ids,omitempty"`
	SourcePrefixes      []*IpPrefix            `protobuf:"bytes,2,rep,name=source_prefixes,json=sourcePrefixes,proto3" json:"source_prefixes,omitempty"`
	DestinationNodeIds  [][]byte               `protobuf:"bytes,3,rep,name=destination_node_ids,json=destinationNodeIds,proto3" json:"destination_node_ids,omitempty"`
	DestinationPrefixes []*IpPrefix            `protobuf:"bytes,4,rep,name=destination_prefixes,json=destinationPrefixes,proto3" json:"destination_prefixes,omitempty"`
	IpProtocol          IpProtocol             `protobuf:"varint,5,opt,name=ip_protocol,json=ipProtocol,proto3,enum=laneway.v1.IpProtocol" json:"ip_protocol,omitempty"`
	DestinationPorts    []*PortRange           `protobuf:"bytes,6,rep,name=destination_ports,json=destinationPorts,proto3" json:"destination_ports,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TrafficSelector) Reset() {
	*x = TrafficSelector{}
	mi := &file_laneway_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficSelector) ProtoMessage() {}

func (x *TrafficSelector) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficSelector.ProtoReflect.Descriptor instead.
func (*TrafficSelector) Descriptor() ([]byte, []int) {
	return file_laneway_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficSelector) GetSourceNodeIds() [][]byte {
	if x != nil {
		return x.SourceNodeIds
	}
	return nil
}

func (x *TrafficSelector) GetSourcePrefixes() []*IpPrefix {
	if x != nil {
		return x.SourcePrefixes
	}
	return nil
}

func (x *TrafficSelector) GetDestinationNodeIds() [][]byte {
	if x != nil {
		return x.DestinationNodeIds
	}
	return nil
}

func (x *TrafficSelector) GetDestinationPrefixes() []*IpPrefix {
	if x != nil {
		return x.DestinationPrefixes
	}
	return nil
}

func (x *TrafficSelector) GetIpProtocol() IpProtocol {
	if x != nil {
		return x.IpProtocol
	}
	return IpProtocol_IP_PROTOCOL_UNSPECIFIED
}

func (x *TrafficSelector) GetDestinationPorts() []*PortRange {
	if x != nil {
		return x.DestinationPorts
	}
	return nil
}

type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        []byte                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Priority      uint32                 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Action        PolicyAction           `protobuf:"varint,3,opt,name=action,proto3,enum=laneway.v1.PolicyAction" json:"action,omitempty"`
	Selector      *TrafficSelector       `protobuf:"bytes,4,opt,name=selector,proto3" json:"selector,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_laneway_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_laneway_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyRule) GetRuleId() []byte {
	if x != nil {
		return x.RuleId
	}
	return nil
}

func (x *PolicyRule) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PolicyRule) GetAction() PolicyAction {
	if x != nil {
		return x.Action
	}
	return PolicyAction_POLICY_ACTION_UNSPECIFIED
}

func (x *PolicyRule) GetSelector() *TrafficSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *PolicyRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PolicySnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NetworkId          []byte                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ConfigurationEpoch uint64                 `protobuf:"varint,2,opt,name=configuration_epoch,json=configurationEpoch,proto3" json:"configuration_epoch,omitempty"`
	// Rules are evaluated by ascending priority, then lexicographic rule_id.
	Rules         []*PolicyRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	DefaultAction PolicyAction  `protobuf:"varint,4,opt,name=default_action,json=defaultAction,proto3,enum=laneway.v1.PolicyAction" json:"default_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySnapshot) Reset() {
	*x = PolicySnapshot{}
	mi := &file_laneway_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySnapshot) ProtoMessage() {}

func (x *PolicySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySnapshot.ProtoReflect.Descriptor instead.
func (*PolicySnapshot) Descriptor() ([]byte, []int) {
	return file_laneway_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicySnapshot) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *PolicySnapshot) GetConfigurationEpoch() uint64 {
	if x != nil {
		return x.ConfigurationEpoch
	}
	return 0
}

func (x *PolicySnapshot) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *PolicySnapshot) GetDefaultAction() PolicyAction {
	if x != nil {
		return x.DefaultAction
	}
	return PolicyAction_POLICY_ACTION_UNSPECIFIED
}

var File_laneway_v1_policy_proto protoreflect.FileDescriptor

const file_laneway_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x17laneway/v1/policy.proto\x12\n" +
	"laneway.v1\x1a\x17laneway/v1/routes.proto\"5\n" +
	"\tPortRange\x12\x14\n" +
	"\x05first\x18\x01 \x01(\rR\x05first\x12\x12\n" +
	"\x04last\x18\x02 \x01(\rR\x04last\"\xf0\x02\n" +
	"\x0fTrafficSelector\x12&\n" +
	"\x0fsource_node_ids\x18\x01 \x03(\fR\rsourceNodeIds\x12=\n" +
	"\x0fsource_prefixes\x18\x02 \x03(\v2\x14.laneway.v1.IpPrefixR\x0esourcePrefixes\x120\n" +
	"\x14destination_node_ids\x18\x03 \x03(\fR\x12destinationNodeIds\x12G\n" +
	"\x14destination_prefixes\x18\x04 \x03(\v2\x14.laneway.v1.IpPrefixR\x13destinationPrefixes\x127\n" +
	"\vip_protocol\x18\x05 \x01(\x0e2\x16.laneway.v1.IpProtocolR\n" +
	"ipProtocol\x12B\n" +
	"\x11destination_ports\x18\x06 \x03(\v2\x15.laneway.v1.PortRangeR\x10destinationPorts\"\xce\x01\n" +
	"\n" +
	"PolicyRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\fR\x06ruleId\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\rR\bpriority\x120\n" +
	"\x06action\x18\x03 \x01(\x0e2\x18.laneway.v1.PolicyActionR\x06action\x127\n" +
	"\bselector\x18\x04 \x01(\v2\x1b.laneway.v1.TrafficSelectorR\bselector\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xcf\x01\n" +
	"\x0ePolicySnapshot\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\x12/\n" +
	"\x13configuration_epoch\x18\x02 \x01(\x04R\x12configurationEpoch\x12,\n" +
	"\x05rules\x18\x03 \x03(\v2\x16.laneway.v1.PolicyRuleR\x05rules\x12?\n" +
	"\x0edefault_action\x18\x04 \x01(\x0e2\x18.laneway.v1.PolicyActionR\rdefaultAction*_\n" +
	"\fPolicyAction\x12\x1d\n" +
	"\x19POLICY_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14POLICY_ACTION_ACCEPT\x10\x01\x12\x16\n" +
	"\x12POLICY_ACTION_DENY\x10\x02*\x97\x01\n" +
	"\n" +
	"IpProtocol\x12\x1b\n" +
	"\x17IP_PROTOCOL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10IP_PROTOCOL_ICMP\x10\x01\x12\x13\n" +
	"\x0fIP_PROTOCOL_TCP\x10\x06\x12\x13\n" +
	"\x0fIP_PROTOCOL_UDP\x10\x11\x12\x16\n" +
	"\x12IP_PROTOCOL_ICMPV6\x10:\x12\x14\n" +
	"\x0fIP_PROTOCOL_ANY\x10\x80\x02B6Z4github.com/Doout/laneway/go/api/laneway/v1;lanewayv1b\x06proto3"

var (
	file_laneway_v1_policy_proto_rawDescOnce sync.Once
	file_laneway_v1_policy_proto_rawDescData []byte
)

func file_laneway_v1_policy_proto_rawDescGZIP() []byte {
	file_laneway_v1_policy_proto_rawDescOnce.Do(func() {
		file_laneway_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laneway_v1_policy_proto_rawDesc), len(file_laneway_v1_policy_proto_rawDesc)))
	})
	return file_laneway_v1_policy_proto_rawDescData
}

var file_laneway_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_laneway_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_laneway_v1_policy_proto_goTypes = []any{
	(PolicyAction)(0),       // 0: laneway.v1.PolicyAction
	(IpProtocol)(0),         // 1: laneway.v1.IpProtocol
	(*PortRange)(nil),       // 2: laneway.v1.PortRange
	(*TrafficSelector)(nil), // 3: laneway.v1.TrafficSelector
	(*PolicyRule)(nil),      // 4: laneway.v1.PolicyRule
	(*PolicySnapshot)(nil),  // 5: laneway.v1.PolicySnapshot
	(*IpPrefix)(nil),        // 6: laneway.v1.IpPrefix
}
var file_laneway_v1_policy_proto_depIdxs = []int32{
	6, // 0: laneway.v1.TrafficSelector.source_prefixes:type_name -> laneway.v1.IpPrefix
	6, // 1: laneway.v1.TrafficSelector.destination_prefixes:type_name -> laneway.v1.IpPrefix
	1, // 2: laneway.v1.TrafficSelector.ip_protocol:type_name -> laneway.v1.IpProtocol
	2, // 3: laneway.v1.TrafficSelector.destination_ports:type_name -> laneway.v1.PortRange
	0, // 4: laneway.v1.PolicyRule.action:type_name -> laneway.v1.PolicyAction
	3, // 5: laneway.v1.PolicyRule.selector:type_name -> laneway.v1.TrafficSelector
	4, // 6: laneway.v1.PolicySnapshot.rules:type_name -> laneway.v1.PolicyRule
	0, // 7: laneway.v1.PolicySnapshot.default_action:type_name -> laneway.v1.PolicyAction
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_laneway_v1_policy_proto_init() }
func file_laneway_v1_policy_proto_init() {
	if File_laneway_v1_policy_proto != nil {
		return
	}
	file_laneway_v1_routes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laneway_v1_policy_proto_rawDesc), len(file_laneway_v1_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laneway_v1_policy_proto_goTypes,
		DependencyIndexes: file_laneway_v1_policy_proto_depIdxs,
		EnumInfos:         file_laneway_v1_policy_proto_enumTypes,
		MessageInfos:      file_laneway_v1_policy_proto_msgTypes,
	}.Build()
	File_laneway_v1_policy_proto = out.File
	file_laneway_v1_policy_proto_goTypes = nil
	file_laneway_v1_policy_proto_depIdxs = nil
}
