// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: laneway/v1/relay.proto

package lanewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointTransport int32

const (
	EndpointTransport_ENDPOINT_TRANSPORT_UNSPECIFIED EndpointTransport = 0
	EndpointTransport_ENDPOINT_TRANSPORT_QUIC_UDP    EndpointTransport = 1
	EndpointTransport_ENDPOINT_TRANSPORT_TLS_TCP     EndpointTransport = 2
)

// Enum value maps for EndpointTransport.
var (
	EndpointTransport_name = map[int32]string{
		0: "ENDPOINT_TRANSPORT_UNSPECIFIED",
		1: "ENDPOINT_TRANSPORT_QUIC_UDP",
		2: "ENDPOINT_TRANSPORT_TLS_TCP",
	}
	EndpointTransport_value = map[string]int32{
		"ENDPOINT_TRANSPORT_UNSPECIFIED": 0,
		"ENDPOINT_TRANSPORT_QUIC_UDP":    1,
		"ENDPOINT_TRANSPORT_TLS_TCP":     2,
	}
)

func (x EndpointTransport) Enum() *EndpointTransport {
	p := new(EndpointTransport)
	*p = x
	return p
}

func (x EndpointTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_relay_proto_enumTypes[0].Descriptor()
}

func (EndpointTransport) Type() protoreflect.EnumType {
	return &file_laneway_v1_relay_proto_enumTypes[0]
}

func (x EndpointTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointTransport.Descriptor instead.
func (EndpointTransport) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_relay_proto_rawDescGZIP(), []int{0}
}

type RelayRegister struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestedMaxRoutes uint32                 `protobuf:"varint,2,opt,name=requested_max_routes,json=requestedMaxRoutes,proto3" json:"requested_max_routes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayRegister) Reset() {
	*x = RelayRegister{}
	mi := &file_laneway_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRegister) ProtoMessage() {}

func (x *RelayRegister) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRegister.ProtoReflect.Descriptor instead.
func (*RelayRegister) Descriptor() ([]byte, []int) {
	return file_laneway_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRegister) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *RelayRegister) GetRequestedMaxRoutes() uint32 {
	if x != nil {
		return x.RequestedMaxRoutes
	}
	return 0
}

type RouteHandleBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Handle zero is reserved and must not be allocated.
	RouteHandle      uint32 `protobuf:"fixed32,1,opt,name=route_handle,json=routeHandle,proto3" json:"route_handle,omitempty"`
	PeerNodeId       []byte `protobuf:"bytes,2,opt,name=peer_node_id,json=peerNodeId,proto3" json:"peer_node_id,omitempty"`
	MaxPacketPayload uint32 `protobuf:"varint,3,opt,name=max_packet_payload,json=maxPacketPayload,proto3" json:"max_packet_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteHandleBinding) Reset() {
	*x = RouteHandleBinding{}
	mi := &file_laneway_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteHandleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteHandleBinding) ProtoMessage() {}

func (x *RouteHandleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteHandleBinding.ProtoReflect.Descriptor instead.
func (*RouteHandleBinding) Descriptor() ([]byte, []int) {
	return file_laneway_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RouteHandleBinding) GetRouteHandle() uint32 {
	if x != nil {
		return x.RouteHandle
	}
	return 0
}

func (x *RouteHandleBinding) GetPeerNodeId() []byte {
	if x != nil {
		return x.PeerNodeId
	}
	return nil
}

func (x *RouteHandleBinding) GetMaxPacketPayload() uint32 {
	if x != nil {
		return x.MaxPacketPayload
	}
	return 0
}

type RouteHandleRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteHandle   uint32                 `protobuf:"fixed32,1,opt,name=route_handle,json=routeHandle,proto3" json:"route_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteHandleRelease) Reset() {
	*x = RouteHandleRelease{}
	mi := &file_laneway_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteHandleRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteHandleRelease) ProtoMessage() {}

func (x *RouteHandleRelease) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteHandleRelease.ProtoReflect.Descriptor instead.
func (*RouteHandleRelease) Descriptor() ([]byte, []int) {
	return file_laneway_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *RouteHandleRelease) GetRouteHandle() uint32 {
	if x != nil {
		return x.RouteHandle
	}
	return 0
}

type EndpointCandidate struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IpAddress []byte                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Port      uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Transport EndpointTransport      `protobuf:"varint,4,opt,name=transport,proto3,enum=laneway.v1.EndpointTransport" json:"transport,omitempty"`
	Priority  uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// Set by the authenticated relay when it forwards an observed endpoint.
	// Publishers MUST leave these fields empty; receivers require 16 bytes.
	RendezvousToken []byte `protobuf:"bytes,6,opt,name=rendezvous_token,json=rendezvousToken,proto3" json:"rendezvous_token,omitempty"`
	// Coordinated probe start in Unix nanoseconds. Generated by the relay.
	ProbeStartUnixNano uint64 `protobuf:"fixed64,7,opt,name=probe_start_unix_nano,json=probeStartUnixNano,proto3" json:"probe_start_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EndpointCandidate) Reset() {
	*x = EndpointCandidate{}
	mi := &file_laneway_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointCandidate) ProtoMessage() {}

func (x *EndpointCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointCandidate.ProtoReflect.Descriptor instead.
func (*EndpointCandidate) Descriptor() ([]byte, []int) {
	return file_laneway_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointCandidate) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *EndpointCandidate) GetIpAddress() []byte {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

func (x *EndpointCandidate) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndpointCandidate) GetTransport() EndpointTransport {
	if x != nil {
		return x.Transport
	}
	return EndpointTransport_ENDPOINT_TRANSPORT_UNSPECIFIED
}

func (x *EndpointCandidate) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EndpointCandidate) GetRendezvousToken() []byte {
	if x != nil {
		return x.RendezvousToken
	}
	return nil
}

func (x *EndpointCandidate) GetProbeStartUnixNano() uint64 {
	if x != nil {
		return x.ProbeStartUnixNano
	}
	return 0
}

type RelayEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*RelayEnvelope_Register
	//	*RelayEnvelope_RouteHandleBinding
	//	*RelayEnvelope_RouteHandleRelease
	//	*RelayEnvelope_EndpointCandidate
	//	*RelayEnvelope_Error
	Body          isRelayEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEnvelope) Reset() {
	*x = RelayEnvelope{}
	mi := &file_laneway_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEnvelope) ProtoMessage() {}

func (x *RelayEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEnvelope.ProtoReflect.Descriptor instead.
func (*RelayEnvelope) Descriptor() ([]byte, []int) {
	return file_laneway_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *RelayEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RelayEnvelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RelayEnvelope) GetBody() isRelayEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RelayEnvelope) GetRegister() *RelayRegister {
	if x != nil {
		if x, ok := x.Body.(*RelayEnvelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *RelayEnvelope) GetRouteHandleBinding() *RouteHandleBinding {
	if x != nil {
		if x, ok := x.Body.(*RelayEnvelope_RouteHandleBinding); ok {
			return x.RouteHandleBinding
		}
	}
	return nil
}

func (x *RelayEnvelope) GetRouteHandleRelease() *RouteHandleRelease {
	if x != nil {
		if x, ok := x.Body.(*RelayEnvelope_RouteHandleRelease); ok {
			return x.RouteHandleRelease
		}
	}
	return nil
}

func (x *RelayEnvelope) GetEndpointCandidate() *EndpointCandidate {
	if x != nil {
		if x, ok := x.Body.(*RelayEnvelope_EndpointCandidate); ok {
			return x.EndpointCandidate
		}
	}
	return nil
}

func (x *RelayEnvelope) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Body.(*RelayEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRelayEnvelope_Body interface {
	isRelayEnvelope_Body()
}

type RelayEnvelope_Register struct {
	Register *RelayRegister `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type RelayEnvelope_RouteHandleBinding struct {
	RouteHandleBinding *RouteHandleBinding `protobuf:"bytes,11,opt,name=route_handle_binding,json=routeHandleBinding,proto3,oneof"`
}

type RelayEnvelope_RouteHandleRelease struct {
	RouteHandleRelease *RouteHandleRelease `protobuf:"bytes,12,opt,name=route_handle_release,json=routeHandleRelease,proto3,oneof"`
}

type RelayEnvelope_EndpointCandidate struct {
	EndpointCandidate *EndpointCandidate `protobuf:"bytes,13,opt,name=endpoint_candidate,json=endpointCandidate,proto3,oneof"`
}

type RelayEnvelope_Error struct {
	Error *ProtocolError `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

func (*RelayEnvelope_Register) isRelayEnvelope_Body() {}

func (*RelayEnvelope_RouteHandleBinding) isRelayEnvelope_Body() {}

func (*RelayEnvelope_RouteHandleRelease) isRelayEnvelope_Body() {}

func (*RelayEnvelope_EndpointCandidate) isRelayEnvelope_Body() {}

func (*RelayEnvelope_Error) isRelayEnvelope_Body() {}

var File_laneway_v1_relay_proto protoreflect.FileDescriptor

const file_laneway_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x16laneway/v1/relay.proto\x12\n" +
	"laneway.v1\x1a\x18laneway/v1/control.proto\"`\n" +
	"\rRelayRegister\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x120\n" +
	"\x14requested_max_routes\x18\x02 \x01(\rR\x12requestedMaxRoutes\"\x87\x01\n" +
	"\x12RouteHandleBinding\x12!\n" +
	"\froute_handle\x18\x01 \x01(\aR\vrouteHandle\x12 \n" +
	"\fpeer_node_id\x18\x02 \x01(\fR\n" +
	"peerNodeId\x12,\n" +
	"\x12max_packet_payload\x18\x03 \x01(\rR\x10maxPacketPayload\"7\n" +
	"\x12RouteHandleRelease\x12!\n" +
	"\froute_handle\x18\x01 \x01(\aR\vrouteHandle\"\x96\x02\n" +
	"\x11EndpointCandidate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\fR\tipAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12;\n" +
	"\ttransport\x18\x04 \x01(\x0e2\x1d.laneway.v1.EndpointTransportR\ttransport\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\x12)\n" +
	"\x10rendezvous_token\x18\x06 \x01(\fR\x0frendezvousToken\x121\n" +
	"\x15probe_start_unix_nano\x18\a \x01(\x06R\x12probeStartUnixNano\"\xbe\x03\n" +
	"\rRelayEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x127\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x19.laneway.v1.RelayRegisterH\x00R\bregister\x12R\n" +
	"\x14route_handle_binding\x18\v \x01(\v2\x1e.laneway.v1.RouteHandleBindingH\x00R\x12routeHandleBinding\x12R\n" +
	"\x14route_handle_release\x18\f \x01(\v2\x1e.laneway.v1.RouteHandleReleaseH\x00R\x12routeHandleRelease\x12N\n" +
	"\x12endpoint_candidate\x18\r \x01(\v2\x1d.laneway.v1.EndpointCandidateH\x00R\x11endpointCandidate\x121\n" +
	"\x05error\x18\x0e \x01(\v2\x19.laneway.v1.ProtocolErrorH\x00R\x05errorB\x06\n" +
	"\x04body*x\n" +
	"\x11EndpointTransport\x12\"\n" +
	"\x1eENDPOINT_TRANSPORT_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bENDPOINT_TRANSPORT_QUIC_UDP\x10\x01\x12\x1e\n" +
	"\x1aENDPOINT_TRANSPORT_TLS_TCP\x10\x02B6Z4github.com/Doout/laneway/go/api/laneway/v1;lanewayv1b\x06proto3"

var (
	file_laneway_v1_relay_proto_rawDescOnce sync.Once
	file_laneway_v1_relay_proto_rawDescData []byte
)

func file_laneway_v1_relay_proto_rawDescGZIP() []byte {
	file_laneway_v1_relay_proto_rawDescOnce.Do(func() {
		file_laneway_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laneway_v1_relay_proto_rawDesc), len(file_laneway_v1_relay_proto_rawDesc)))
	})
	return file_laneway_v1_relay_proto_rawDescData
}

var file_laneway_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_laneway_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_laneway_v1_relay_proto_goTypes = []any{
	(EndpointTransport)(0),     // 0: laneway.v1.EndpointTransport
	(*RelayRegister)(nil),      // 1: laneway.v1.RelayRegister
	(*RouteHandleBinding)(nil), // 2: laneway.v1.RouteHandleBinding
	(*RouteHandleRelease)(nil), // 3: laneway.v1.RouteHandleRelease
	(*EndpointCandidate)(nil),  // 4: laneway.v1.EndpointCandidate
	(*RelayEnvelope)(nil),      // 5: laneway.v1.RelayEnvelope
	(*ProtocolError)(nil),      // 6: laneway.v1.ProtocolError
}
var file_laneway_v1_relay_proto_depIdxs = []int32{
	0, // 0: laneway.v1.EndpointCandidate.transport:type_name -> laneway.v1.EndpointTransport
	1, // 1: laneway.v1.RelayEnvelope.register:type_name -> laneway.v1.RelayRegister
	2, // 2: laneway.v1.RelayEnvelope.route_handle_binding:type_name -> laneway.v1.RouteHandleBinding
	3, // 3: laneway.v1.RelayEnvelope.route_handle_release:type_name -> laneway.v1.RouteHandleRelease
	4, // 4: laneway.v1.RelayEnvelope.endpoint_candidate:type_name -> laneway.v1.EndpointCandidate
	6, // 5: laneway.v1.RelayEnvelope.error:type_name -> laneway.v1.ProtocolError
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_laneway_v1_relay_proto_init() }
func file_laneway_v1_relay_proto_init() {
	if File_laneway_v1_relay_proto != nil {
		return
	}
	file_laneway_v1_control_proto_init()
	file_laneway_v1_relay_proto_msgTypes[4].OneofWrappers = []any{
		(*RelayEnvelope_Register)(nil),
		(*RelayEnvelope_RouteHandleBinding)(nil),
		(*RelayEnvelope_RouteHandleRelease)(nil),
		(*RelayEnvelope_EndpointCandidate)(nil),
		(*RelayEnvelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laneway_v1_relay_proto_rawDesc), len(file_laneway_v1_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laneway_v1_relay_proto_goTypes,
		DependencyIndexes: file_laneway_v1_relay_proto_depIdxs,
		EnumInfos:         file_laneway_v1_relay_proto_enumTypes,
		MessageInfos:      file_laneway_v1_relay_proto_msgTypes,
	}.Build()
	File_laneway_v1_relay_proto = out.File
	file_laneway_v1_relay_proto_goTypes = nil
	file_laneway_v1_relay_proto_depIdxs = nil
}
