// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: laneway/v1/routes.proto

package lanewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteKind int32

const (
	RouteKind_ROUTE_KIND_UNSPECIFIED RouteKind = 0
	RouteKind_ROUTE_KIND_OVERLAY     RouteKind = 1
	RouteKind_ROUTE_KIND_SUBNET      RouteKind = 2
	RouteKind_ROUTE_KIND_EXIT        RouteKind = 3
)

// Enum value maps for RouteKind.
var (
	RouteKind_name = map[int32]string{
		0: "ROUTE_KIND_UNSPECIFIED",
		1: "ROUTE_KIND_OVERLAY",
		2: "ROUTE_KIND_SUBNET",
		3: "ROUTE_KIND_EXIT",
	}
	RouteKind_value = map[string]int32{
		"ROUTE_KIND_UNSPECIFIED": 0,
		"ROUTE_KIND_OVERLAY":     1,
		"ROUTE_KIND_SUBNET":      2,
		"ROUTE_KIND_EXIT":        3,
	}
)

func (x RouteKind) Enum() *RouteKind {
	p := new(RouteKind)
	*p = x
	return p
}

func (x RouteKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteKind) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_routes_proto_enumTypes[0].Descriptor()
}

func (RouteKind) Type() protoreflect.EnumType {
	return &file_laneway_v1_routes_proto_enumTypes[0]
}

func (x RouteKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteKind.Descriptor instead.
func (RouteKind) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{0}
}

type RouteAdvertisementMode int32

const (
	RouteAdvertisementMode_ROUTE_ADVERTISEMENT_MODE_UNSPECIFIED RouteAdvertisementMode = 0
	RouteAdvertisementMode_ROUTE_ADVERTISEMENT_MODE_NAT         RouteAdvertisementMode = 1
	RouteAdvertisementMode_ROUTE_ADVERTISEMENT_MODE_ROUTED      RouteAdvertisementMode = 2
)

// Enum value maps for RouteAdvertisementMode.
var (
	RouteAdvertisementMode_name = map[int32]string{
		0: "ROUTE_ADVERTISEMENT_MODE_UNSPECIFIED",
		1: "ROUTE_ADVERTISEMENT_MODE_NAT",
		2: "ROUTE_ADVERTISEMENT_MODE_ROUTED",
	}
	RouteAdvertisementMode_value = map[string]int32{
		"ROUTE_ADVERTISEMENT_MODE_UNSPECIFIED": 0,
		"ROUTE_ADVERTISEMENT_MODE_NAT":         1,
		"ROUTE_ADVERTISEMENT_MODE_ROUTED":      2,
	}
)

func (x RouteAdvertisementMode) Enum() *RouteAdvertisementMode {
	p := new(RouteAdvertisementMode)
	*p = x
	return p
}

func (x RouteAdvertisementMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteAdvertisementMode) Descriptor() protoreflect.EnumDescriptor {
	return file_laneway_v1_routes_proto_enumTypes[1].Descriptor()
}

func (RouteAdvertisementMode) Type() protoreflect.EnumType {
	return &file_laneway_v1_routes_proto_enumTypes[1]
}

func (x RouteAdvertisementMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteAdvertisementMode.Descriptor instead.
func (RouteAdvertisementMode) EnumDescriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{1}
}

type IpPrefix struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network-order IPv4 (4 bytes) or IPv6 (16 bytes). Host bits must be zero.
	Address       []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength  uint32 `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpPrefix) Reset() {
	*x = IpPrefix{}
	mi := &file_laneway_v1_routes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpPrefix) ProtoMessage() {}

func (x *IpPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_routes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpPrefix.ProtoReflect.Descriptor instead.
func (*IpPrefix) Descriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{0}
}

func (x *IpPrefix) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *IpPrefix) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

type Route struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Destination *IpPrefix              `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ViaNodeId   []byte                 `protobuf:"bytes,2,opt,name=via_node_id,json=viaNodeId,proto3" json:"via_node_id,omitempty"`
	Kind        RouteKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=laneway.v1.RouteKind" json:"kind,omitempty"`
	Metric      uint32                 `protobuf:"varint,4,opt,name=metric,proto3" json:"metric,omitempty"`
	// Stable controller-assigned identifier; exactly 16 bytes.
	RouteId []byte `protobuf:"bytes,5,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	// NAT or routed forwarding semantics for subnet and exit routes. Overlay
	// routes leave this unspecified.
	Mode          RouteAdvertisementMode `protobuf:"varint,6,opt,name=mode,proto3,enum=laneway.v1.RouteAdvertisementMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_laneway_v1_routes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_routes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetDestination() *IpPrefix {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Route) GetViaNodeId() []byte {
	if x != nil {
		return x.ViaNodeId
	}
	return nil
}

func (x *Route) GetKind() RouteKind {
	if x != nil {
		return x.Kind
	}
	return RouteKind_ROUTE_KIND_UNSPECIFIED
}

func (x *Route) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Route) GetRouteId() []byte {
	if x != nil {
		return x.RouteId
	}
	return nil
}

func (x *Route) GetMode() RouteAdvertisementMode {
	if x != nil {
		return x.Mode
	}
	return RouteAdvertisementMode_ROUTE_ADVERTISEMENT_MODE_UNSPECIFIED
}

type RouteSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NetworkId          []byte                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ConfigurationEpoch uint64                 `protobuf:"varint,2,opt,name=configuration_epoch,json=configurationEpoch,proto3" json:"configuration_epoch,omitempty"`
	Routes             []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RouteSnapshot) Reset() {
	*x = RouteSnapshot{}
	mi := &file_laneway_v1_routes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSnapshot) ProtoMessage() {}

func (x *RouteSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_routes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSnapshot.ProtoReflect.Descriptor instead.
func (*RouteSnapshot) Descriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{2}
}

func (x *RouteSnapshot) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *RouteSnapshot) GetConfigurationEpoch() uint64 {
	if x != nil {
		return x.ConfigurationEpoch
	}
	return 0
}

func (x *RouteSnapshot) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     []byte                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	FromEpoch     uint64                 `protobuf:"varint,2,opt,name=from_epoch,json=fromEpoch,proto3" json:"from_epoch,omitempty"`
	ToEpoch       uint64                 `protobuf:"varint,3,opt,name=to_epoch,json=toEpoch,proto3" json:"to_epoch,omitempty"`
	Upsert        []*Route               `protobuf:"bytes,4,rep,name=upsert,proto3" json:"upsert,omitempty"`
	RemoveRouteId [][]byte               `protobuf:"bytes,5,rep,name=remove_route_id,json=removeRouteId,proto3" json:"remove_route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteDelta) Reset() {
	*x = RouteDelta{}
	mi := &file_laneway_v1_routes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDelta) ProtoMessage() {}

func (x *RouteDelta) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_routes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDelta.ProtoReflect.Descriptor instead.
func (*RouteDelta) Descriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{3}
}

func (x *RouteDelta) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *RouteDelta) GetFromEpoch() uint64 {
	if x != nil {
		return x.FromEpoch
	}
	return 0
}

func (x *RouteDelta) GetToEpoch() uint64 {
	if x != nil {
		return x.ToEpoch
	}
	return 0
}

func (x *RouteDelta) GetUpsert() []*Route {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *RouteDelta) GetRemoveRouteId() [][]byte {
	if x != nil {
		return x.RemoveRouteId
	}
	return nil
}

type RouteAdvertisement struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Advertiser            *NodeRef               `protobuf:"bytes,1,opt,name=advertiser,proto3" json:"advertiser,omitempty"`
	AdvertisementId       []byte                 `protobuf:"bytes,2,opt,name=advertisement_id,json=advertisementId,proto3" json:"advertisement_id,omitempty"`
	Prefixes              []*IpPrefix            `protobuf:"bytes,3,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	Mode                  RouteAdvertisementMode `protobuf:"varint,4,opt,name=mode,proto3,enum=laneway.v1.RouteAdvertisementMode" json:"mode,omitempty"`
	ValidUntilUnixSeconds uint64                 `protobuf:"varint,5,opt,name=valid_until_unix_seconds,json=validUntilUnixSeconds,proto3" json:"valid_until_unix_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RouteAdvertisement) Reset() {
	*x = RouteAdvertisement{}
	mi := &file_laneway_v1_routes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAdvertisement) ProtoMessage() {}

func (x *RouteAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_routes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAdvertisement.ProtoReflect.Descriptor instead.
func (*RouteAdvertisement) Descriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{4}
}

func (x *RouteAdvertisement) GetAdvertiser() *NodeRef {
	if x != nil {
		return x.Advertiser
	}
	return nil
}

func (x *RouteAdvertisement) GetAdvertisementId() []byte {
	if x != nil {
		return x.AdvertisementId
	}
	return nil
}

func (x *RouteAdvertisement) GetPrefixes() []*IpPrefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *RouteAdvertisement) GetMode() RouteAdvertisementMode {
	if x != nil {
		return x.Mode
	}
	return RouteAdvertisementMode_ROUTE_ADVERTISEMENT_MODE_UNSPECIFIED
}

func (x *RouteAdvertisement) GetValidUntilUnixSeconds() uint64 {
	if x != nil {
		return x.ValidUntilUnixSeconds
	}
	return 0
}

type RouteWithdrawal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Advertiser      *NodeRef               `protobuf:"bytes,1,opt,name=advertiser,proto3" json:"advertiser,omitempty"`
	AdvertisementId []byte                 `protobuf:"bytes,2,opt,name=advertisement_id,json=advertisementId,proto3" json:"advertisement_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteWithdrawal) Reset() {
	*x = RouteWithdrawal{}
	mi := &file_laneway_v1_routes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteWithdrawal) ProtoMessage() {}

func (x *RouteWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_laneway_v1_routes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteWithdrawal.ProtoReflect.Descriptor instead.
func (*RouteWithdrawal) Descriptor() ([]byte, []int) {
	return file_laneway_v1_routes_proto_rawDescGZIP(), []int{5}
}

func (x *RouteWithdrawal) GetAdvertiser() *NodeRef {
	if x != nil {
		return x.Advertiser
	}
	return nil
}

func (x *RouteWithdrawal) GetAdvertisementId() []byte {
	if x != nil {
		return x.AdvertisementId
	}
	return nil
}

var File_laneway_v1_routes_proto protoreflect.FileDescriptor

const file_laneway_v1_routes_proto_rawDesc = "" +
	"\n" +
	"\x17laneway/v1/routes.proto\x12\n" +
	"laneway.v1\x1a\x18laneway/v1/control.proto\"I\n" +
	"\bIpPrefix\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12#\n" +
	"\rprefix_length\x18\x02 \x01(\rR\fprefixLength\"\xf5\x01\n" +
	"\x05Route\x126\n" +
	"\vdestination\x18\x01 \x01(\v2\x14.laneway.v1.IpPrefixR\vdestination\x12\x1e\n" +
	"\vvia_node_id\x18\x02 \x01(\fR\tviaNodeId\x12)\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x15.laneway.v1.RouteKindR\x04kind\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\rR\x06metric\x12\x19\n" +
	"\broute_id\x18\x05 \x01(\fR\arouteId\x126\n" +
	"\x04mode\x18\x06 \x01(\x0e2\".laneway.v1.RouteAdvertisementModeR\x04mode\"\x8a\x01\n" +
	"\rRouteSnapshot\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\x12/\n" +
	"\x13configuration_epoch\x18\x02 \x01(\x04R\x12configurationEpoch\x12)\n" +
	"\x06routes\x18\x03 \x03(\v2\x11.laneway.v1.RouteR\x06routes\"\xb8\x01\n" +
	"\n" +
	"RouteDelta\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\fR\tnetworkId\x12\x1d\n" +
	"\n" +
	"from_epoch\x18\x02 \x01(\x04R\tfromEpoch\x12\x19\n" +
	"\bto_epoch\x18\x03 \x01(\x04R\atoEpoch\x12)\n" +
	"\x06upsert\x18\x04 \x03(\v2\x11.laneway.v1.RouteR\x06upsert\x12&\n" +
	"\x0fremove_route_id\x18\x05 \x03(\fR\rremoveRouteId\"\x97\x02\n" +
	"\x12RouteAdvertisement\x123\n" +
	"\n" +
	"advertiser\x18\x01 \x01(\v2\x13.laneway.v1.NodeRefR\n" +
	"advertiser\x12)\n" +
	"\x10advertisement_id\x18\x02 \x01(\fR\x0fadvertisementId\x120\n" +
	"\bprefixes\x18\x03 \x03(\v2\x14.laneway.v1.IpPrefixR\bprefixes\x126\n" +
	"\x04mode\x18\x04 \x01(\x0e2\".laneway.v1.RouteAdvertisementModeR\x04mode\x127\n" +
	"\x18valid_until_unix_seconds\x18\x05 \x01(\x04R\x15validUntilUnixSeconds\"q\n" +
	"\x0fRouteWithdrawal\x123\n" +
	"\n" +
	"advertiser\x18\x01 \x01(\v2\x13.laneway.v1.NodeRefR\n" +
	"advertiser\x12)\n" +
	"\x10advertisement_id\x18\x02 \x01(\fR\x0fadvertisementId*k\n" +
	"\tRouteKind\x12\x1a\n" +
	"\x16ROUTE_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ROUTE_KIND_OVERLAY\x10\x01\x12\x15\n" +
	"\x11ROUTE_KIND_SUBNET\x10\x02\x12\x13\n" +
	"\x0fROUTE_KIND_EXIT\x10\x03*\x89\x01\n" +
	"\x16RouteAdvertisementMode\x12(\n" +
	"$ROUTE_ADVERTISEMENT_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cROUTE_ADVERTISEMENT_MODE_NAT\x10\x01\x12#\n" +
	"\x1fROUTE_ADVERTISEMENT_MODE_ROUTED\x10\x02B.Z,laneway.dev/laneway/api/laneway/v1;lanewayv1b\x06proto3"

var (
	file_laneway_v1_routes_proto_rawDescOnce sync.Once
	file_laneway_v1_routes_proto_rawDescData []byte
)

func file_laneway_v1_routes_proto_rawDescGZIP() []byte {
	file_laneway_v1_routes_proto_rawDescOnce.Do(func() {
		file_laneway_v1_routes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laneway_v1_routes_proto_rawDesc), len(file_laneway_v1_routes_proto_rawDesc)))
	})
	return file_laneway_v1_routes_proto_rawDescData
}

var file_laneway_v1_routes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_laneway_v1_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_laneway_v1_routes_proto_goTypes = []any{
	(RouteKind)(0),              // 0: laneway.v1.RouteKind
	(RouteAdvertisementMode)(0), // 1: laneway.v1.RouteAdvertisementMode
	(*IpPrefix)(nil),            // 2: laneway.v1.IpPrefix
	(*Route)(nil),               // 3: laneway.v1.Route
	(*RouteSnapshot)(nil),       // 4: laneway.v1.RouteSnapshot
	(*RouteDelta)(nil),          // 5: laneway.v1.RouteDelta
	(*RouteAdvertisement)(nil),  // 6: laneway.v1.RouteAdvertisement
	(*RouteWithdrawal)(nil),     // 7: laneway.v1.RouteWithdrawal
	(*NodeRef)(nil),             // 8: laneway.v1.NodeRef
}
var file_laneway_v1_routes_proto_depIdxs = []int32{
	2, // 0: laneway.v1.Route.destination:type_name -> laneway.v1.IpPrefix
	0, // 1: laneway.v1.Route.kind:type_name -> laneway.v1.RouteKind
	1, // 2: laneway.v1.Route.mode:type_name -> laneway.v1.RouteAdvertisementMode
	3, // 3: laneway.v1.RouteSnapshot.routes:type_name -> laneway.v1.Route
	3, // 4: laneway.v1.RouteDelta.upsert:type_name -> laneway.v1.Route
	8, // 5: laneway.v1.RouteAdvertisement.advertiser:type_name -> laneway.v1.NodeRef
	2, // 6: laneway.v1.RouteAdvertisement.prefixes:type_name -> laneway.v1.IpPrefix
	1, // 7: laneway.v1.RouteAdvertisement.mode:type_name -> laneway.v1.RouteAdvertisementMode
	8, // 8: laneway.v1.RouteWithdrawal.advertiser:type_name -> laneway.v1.NodeRef
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_laneway_v1_routes_proto_init() }
func file_laneway_v1_routes_proto_init() {
	if File_laneway_v1_routes_proto != nil {
		return
	}
	file_laneway_v1_control_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laneway_v1_routes_proto_rawDesc), len(file_laneway_v1_routes_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laneway_v1_routes_proto_goTypes,
		DependencyIndexes: file_laneway_v1_routes_proto_depIdxs,
		EnumInfos:         file_laneway_v1_routes_proto_enumTypes,
		MessageInfos:      file_laneway_v1_routes_proto_msgTypes,
	}.Build()
	File_laneway_v1_routes_proto = out.File
	file_laneway_v1_routes_proto_goTypes = nil
	file_laneway_v1_routes_proto_depIdxs = nil
}
