// Package pki provides the certificate primitives used by manual Phase 1
// deployments and later by controller-backed enrollment. Private keys are
// generated by the caller-side operation and are never accepted from a CSR.
package pki

import (
	"bytes"
	"crypto"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"net/url"
	"time"

	"github.com/Doout/laneway/go/internal/identity"
)

const DefaultLeafValidity = 30 * 24 * time.Hour

type Material struct {
	CertificateDER []byte
	PrivateKey     crypto.Signer
}

type ServiceRole string

const (
	RoleRelay      ServiceRole = "relay"
	RoleController ServiceRole = "controller"
)

type ServiceIdentity struct {
	NetworkID identity.NetworkID
	ServiceID identity.ID
	Role      ServiceRole
}

func (s ServiceIdentity) URI() (*url.URL, error) {
	if s.NetworkID.IsZero() || s.ServiceID.IsZero() || (s.Role != RoleRelay && s.Role != RoleController) {
		return nil, errors.New("invalid Laneway service identity")
	}
	return &url.URL{
		Scheme: "spiffe",
		Host:   identity.SPIFFETrustDomain,
		Path:   "/network/" + s.NetworkID.String() + "/" + string(s.Role) + "/" + s.ServiceID.String(),
	}, nil
}

func NewAuthority(commonName string, now time.Time, validity time.Duration) (Material, *x509.Certificate, error) {
	if commonName == "" || validity <= 0 {
		return Material{}, nil, errors.New("CA common name and positive validity are required")
	}
	public, private, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return Material{}, nil, fmt.Errorf("generate CA key: %w", err)
	}
	serial, err := randomSerial()
	if err != nil {
		return Material{}, nil, err
	}
	template := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: commonName},
		NotBefore:             now.Add(-time.Minute),
		NotAfter:              now.Add(validity),
		IsCA:                  true,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, public, private)
	if err != nil {
		return Material{}, nil, fmt.Errorf("create CA certificate: %w", err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return Material{}, nil, fmt.Errorf("parse generated CA certificate: %w", err)
	}
	return Material{CertificateDER: der, PrivateKey: private}, cert, nil
}

// IssueIntermediate creates an online issuing CA signed by an existing CA.
// The generated key belongs to the intermediate and can be installed on the
// controller while the parent key remains offline. The certificate cannot
// issue another CA, keeping the supported hierarchy root -> issuer -> leaf.
func IssueIntermediate(parent *x509.Certificate, parentKey crypto.Signer, commonName string, now time.Time, validity time.Duration) (Material, *x509.Certificate, error) {
	if parent == nil || parentKey == nil || !parent.IsCA || commonName == "" || validity <= 0 {
		return Material{}, nil, errors.New("valid parent CA, signer, common name, and positive validity are required")
	}
	if !publicKeysEqual(parent.PublicKey, parentKey.Public()) {
		return Material{}, nil, errors.New("parent CA certificate and private key do not match")
	}
	if now.Add(validity).After(parent.NotAfter) {
		return Material{}, nil, errors.New("intermediate validity exceeds parent CA validity")
	}
	public, private, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return Material{}, nil, fmt.Errorf("generate intermediate key: %w", err)
	}
	serial, err := randomSerial()
	if err != nil {
		return Material{}, nil, err
	}
	template := &x509.Certificate{
		SerialNumber: serial, Subject: pkix.Name{CommonName: commonName},
		NotBefore: now.Add(-time.Minute), NotAfter: now.Add(validity),
		IsCA: true, BasicConstraintsValid: true, MaxPathLen: 0, MaxPathLenZero: true,
		KeyUsage: x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, parent, public, parentKey)
	if err != nil {
		return Material{}, nil, fmt.Errorf("create intermediate certificate: %w", err)
	}
	certificate, err := x509.ParseCertificate(der)
	if err != nil {
		return Material{}, nil, fmt.Errorf("parse generated intermediate certificate: %w", err)
	}
	return Material{CertificateDER: der, PrivateKey: private}, certificate, nil
}

func IssueNode(ca *x509.Certificate, caKey crypto.Signer, node identity.NodeIdentity, now time.Time, validity time.Duration) (Material, *x509.Certificate, error) {
	uri, err := node.URI()
	if err != nil {
		return Material{}, nil, err
	}
	return issue(ca, caKey, "laneway-node-"+node.NodeID.String(), []*url.URL{uri}, nil, nil, now, validity,
		[]x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth, x509.ExtKeyUsageServerAuth})
}

func IssueService(ca *x509.Certificate, caKey crypto.Signer, service ServiceIdentity, dnsNames []string, ips []net.IP, now time.Time, validity time.Duration) (Material, *x509.Certificate, error) {
	uri, err := service.URI()
	if err != nil {
		return Material{}, nil, err
	}
	usages := []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth}
	// Relays serve node connections and also authenticate as mTLS clients when
	// polling the controller. Controller certificates never need client auth.
	if service.Role == RoleRelay {
		usages = append(usages, x509.ExtKeyUsageClientAuth)
	}
	return issue(ca, caKey, "laneway-"+string(service.Role)+"-"+service.ServiceID.String(), []*url.URL{uri}, dnsNames, ips, now, validity, usages)
}

func issue(ca *x509.Certificate, caKey crypto.Signer, commonName string, uris []*url.URL, dnsNames []string, ips []net.IP, now time.Time, validity time.Duration, eku []x509.ExtKeyUsage) (Material, *x509.Certificate, error) {
	if ca == nil || caKey == nil || !ca.IsCA || validity <= 0 {
		return Material{}, nil, errors.New("valid CA, signer, and positive validity are required")
	}
	if now.Add(validity).After(ca.NotAfter) {
		return Material{}, nil, errors.New("leaf validity exceeds CA validity")
	}
	public, private, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return Material{}, nil, fmt.Errorf("generate leaf key: %w", err)
	}
	serial, err := randomSerial()
	if err != nil {
		return Material{}, nil, err
	}
	template := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: commonName},
		NotBefore:             now.Add(-time.Minute),
		NotAfter:              now.Add(validity),
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           eku,
		URIs:                  uris,
		DNSNames:              append([]string(nil), dnsNames...),
		IPAddresses:           append([]net.IP(nil), ips...),
	}
	der, err := x509.CreateCertificate(rand.Reader, template, ca, public, caKey)
	if err != nil {
		return Material{}, nil, fmt.Errorf("create leaf certificate: %w", err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return Material{}, nil, fmt.Errorf("parse generated leaf certificate: %w", err)
	}
	return Material{CertificateDER: der, PrivateKey: private}, cert, nil
}

func CertificatePEM(der []byte) []byte {
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
}

func PrivateKeyPEM(key crypto.Signer) ([]byte, error) {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("marshal private key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}), nil
}

func ParseAuthority(certificatePEM, privateKeyPEM []byte) (*x509.Certificate, crypto.Signer, error) {
	cert, signer, chain, err := ParseAuthorityBundle(certificatePEM, privateKeyPEM)
	if err != nil {
		return nil, nil, err
	}
	if len(chain) != 1 {
		return nil, nil, errors.New("CA file must contain exactly one CERTIFICATE PEM block")
	}
	return cert, signer, nil
}

// ParseAuthorityBundle parses an issuer certificate followed by its parent
// chain. The private key must match the first certificate. Certificates must
// be ordered issuer-first and form one valid CA chain.
func ParseAuthorityBundle(certificatePEM, privateKeyPEM []byte) (*x509.Certificate, crypto.Signer, []*x509.Certificate, error) {
	chain, err := ParseCertificatesPEM(certificatePEM)
	if err != nil || len(chain) == 0 || !chain[0].IsCA {
		return nil, nil, nil, errors.New("invalid CA certificate bundle")
	}
	for i := range len(chain) - 1 {
		if !chain[i+1].IsCA || chain[i].CheckSignatureFrom(chain[i+1]) != nil {
			return nil, nil, nil, errors.New("CA certificate bundle is not an ordered issuer chain")
		}
	}
	keyBlock, rest := pem.Decode(privateKeyPEM)
	if keyBlock == nil || keyBlock.Type != "PRIVATE KEY" || len(rest) != 0 {
		return nil, nil, nil, errors.New("CA key file must contain exactly one PKCS#8 PRIVATE KEY PEM block")
	}
	parsed, err := x509.ParsePKCS8PrivateKey(keyBlock.Bytes)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("parse CA private key: %w", err)
	}
	signer, ok := parsed.(crypto.Signer)
	if !ok {
		return nil, nil, nil, errors.New("CA private key is not a signer")
	}
	if !publicKeysEqual(chain[0].PublicKey, signer.Public()) {
		return nil, nil, nil, errors.New("CA certificate and private key do not match")
	}
	return chain[0], signer, chain, nil
}

// ParseCertificatesPEM accepts only consecutive CERTIFICATE PEM blocks.
func ParseCertificatesPEM(contents []byte) ([]*x509.Certificate, error) {
	var certificates []*x509.Certificate
	for len(contents) != 0 {
		block, rest := pem.Decode(contents)
		if block == nil || block.Type != "CERTIFICATE" {
			return nil, errors.New("certificate bundle contains non-certificate data")
		}
		certificate, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			return nil, errors.New("certificate bundle contains an invalid certificate")
		}
		certificates = append(certificates, certificate)
		contents = rest
	}
	if len(certificates) == 0 {
		return nil, errors.New("certificate bundle is empty")
	}
	return certificates, nil
}

// IssuerChainDER returns the non-self-signed certificates from an issuer-first
// chain. Trust anchors remain out of band and are not sent to enrolled nodes.
func IssuerChainDER(chain []*x509.Certificate) [][]byte {
	result := make([][]byte, 0, len(chain))
	for _, certificate := range chain {
		if certificate == nil || certificate.CheckSignatureFrom(certificate) == nil {
			continue
		}
		result = append(result, append([]byte(nil), certificate.Raw...))
	}
	return result
}

func publicKeysEqual(a, b any) bool {
	aDER, aErr := x509.MarshalPKIXPublicKey(a)
	bDER, bErr := x509.MarshalPKIXPublicKey(b)
	return aErr == nil && bErr == nil && bytes.Equal(aDER, bDER)
}

func randomSerial() (*big.Int, error) {
	limit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, limit)
	if err != nil {
		return nil, fmt.Errorf("generate certificate serial: %w", err)
	}
	if serial.Sign() == 0 {
		return big.NewInt(1), nil
	}
	return serial, nil
}
