export const approvedScreens = [
  ['/sign-in', 'Sign in to Laneway'],
  ['/overview', 'Overview'],
  ['/nodes', '5 Nodes'],
  ['/nodes/new', 'Add node'],
  ['/nodes/new/token', 'Node token issued'],
  ['/nodes/atlas-gateway', 'Node detail'],
  ['/nodes/atlas-gateway/capabilities', 'Edit capabilities'],
  ['/nodes/atlas-gateway/revoke', 'Revoke atlas-gateway?'],
  ['/users', 'Users'],
  ['/users/new', 'Issue user access'],
  ['/users/new/token', 'User token issued'],
  ['/users/platform-operator', 'User enrollment detail'],
  ['/routes', 'Routes'],
  ['/routes/new', 'Create route'],
  ['/routes/rte_01J8KUBEAPI/approve', 'Review Kubernetes API'],
  ['/routes/rte_01J8PROD16', 'Production services'],
  ['/access', 'Access rules'],
  ['/access/new', 'Create access rule'],
  ['/access/acl_01J8PRODOPS', 'Production operators'],
  ['/infrastructure', 'Infrastructure'],
  ['/infrastructure/networks/production', 'Production'],
  ['/infrastructure/relays/new', 'Register relay'],
  ['/security', 'Security'],
  ['/audit', 'Audit events'],
] as const
