services:
  controller:
    image: laneway-controller:dev
    build:
      context: ../..
      dockerfile: deploy/containers/Dockerfile
      target: controller
  relay:
    image: laneway-relay:dev
    build:
      context: ../..
      dockerfile: deploy/containers/Dockerfile
      target: relay
  admin:
    image: laneway-admin:dev
    build:
      context: ../..
      dockerfile: deploy/containers/Dockerfile
      target: admin
  exit-node:
    image: laneway-exit-node:dev
    build:
      context: ../..
      dockerfile: deploy/containers/Dockerfile.exit-node
